### ISSUE TITLE
muh robo birbs BURN

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#1030]
#### Brief description of the issue
Tesh FBPs overheat rapidly at room temp forcing you to use a NIF heatsink or suit and cooling unit.

#### What you expected to happen
Not to die from just trying to exist

#### What actually happened
IT BURNS

#### Steps to reproduce
self-explanatory

#### Code Revision

  56fe763190f94e4210e996cf09460a6ea9dde474
#### Anything else you may wish to add:

*peeps like a bird.*

**Comment by KillianKirilenko** [comment]
This should've been fixed upstream a good... month or two back, at least? It should be fixed whenever #1018 goes through. Or the next one after that maybe.

**Comment by izac112** [comment]
We should have that fixed in the pr if its been fixed already upstream, i just merged the new release in to the pr yesterday.

**Comment by benj8560** [comment]
I was having this issue IG when I posted it soooooo *shrug*

**Comment by benj8560** [comment]
Tesh on hard mode was kinda fun tho

**Comment by izac112** [comment]
Well that is because the pr has not been merged yet so the fixed is not actually on the server.

**Comment by benj8560** [comment]
Ahh I get what you two mean now I'll close this then since the fix is already in existence

**Comment by izac112** [comment]
Oh no you can leave it up, once the pr is merged it will auto close this
