### ISSUE TITLE
Vore broke the wiring down on the second floor.

### ISSUE THREAD

**Issue by lukevale** [Yawn-Wider/YWPolarisVore#113]
#### Brief description of the issue
Down on the first floor, some wires aren't properly mapped, and it leaves alot of the area off the grid entirely.

#### What you expected to happen
for vore not to fuck up with it.

#### What actually happened
Complete loss of power down on the second floor in that wasn't connected already to science or atmos. Mining and telecoms losses power. Simple fix is to go to the second floor stair well and make a path with some wire at a small cross road.

#### Steps to reproduce
- happens on round start.

#### Code Revision
82b918c4c1bbe83554940d9248b405f7c1f4c9d6 
 
#### Anything else you may wish to add:
https://cdn.discordapp.com/attachments/247070327497031680/588922253916504076/unknown.png
The spot where you can do the wire fix.

**Comment by Hawk-v3** [comment]
Y'ok. I'll get this fixed.
