### ISSUE TITLE
Communicators lose connection permanently

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#1151]
#### Brief description of the issue
First issue: The bug where communicators refuse to reconnect after a telecomms outage has returned.

#### What you expected to happen
1st: Communicators to reconnect to the exonet node after t-coms comes back online from powerloss or weather

#### What actually happened
1st: On occasion, communicators will become permanently unable to send or connect to calls, and only able to receive text messages, not send them, requiring admin magic or leaving/coming back (via IC exits) to the shift to fix.

#### Steps to reproduce
First issue:
Step 1: Have either type communicator (handset or watch)
Step 2: Be present for weather outage or power outage of t-comms
Step 3: if you're one of the lucky afflicted, (at least one person per round as I've seen), when comms return, your communicator will permanently show the "disconnected" symbol and not work anymore. This may also occur by being aboard the talon when it travels out of t-comms range.

Possible solution for the first problem: Maybe add a "reboot" function to communicators like that on the PDA or the tablet/laptop's "force shutdown".

#### Code Revision
- Server revision: B:-Using TGS- D:-Using TGS-
Commit: b48f8acdf1ed54d6aff09d53a508ce702820e7b1
TGS version: 4.11.1
DMAPI version: 5.1.1 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
please make a seperate issue for the other problem

**Comment by DeepIndigo** [comment]
Can do.

**Comment by DeepIndigo** [comment]
This is fixed

**Comment by izac112** [comment]
okay closing it then
