### ISSUE TITLE
BIG ISSUE WITH BACKPACKS

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#1160]
#### Brief description of the issue
you can not take things out of them, period.

#### What you expected to happen
Backpacks to not be black holes of no return.

#### What actually happened
Backpacks are black holes of no return.

#### Steps to reproduce
- Spawn with literally anything in your backpack
- Try to take it out
- It vanishes off the little backpack tray but nothing appears in your hand
- re-open backback and find the backpack has reclaimed the item.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:-Using TGS- D:-Using TGS-
Commit: 1119a54de8a14a3b08b4ebd22c89a8046e66ee66
TGS version: 4.11.1
DMAPI version: 5.1.1 
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Holy ass crackers can we go back like, an update or two?

**Comment by Repede** [comment]
Debug log that shows when someone tries pulling an item:

[2021-07-07T00:15:30] Runtime in storage.dm,523: undefined variable /client/var/client
   proc name: remove from storage (/obj/item/weapon/storage/proc/remove_from_storage)
   usr: Red Eyed Shadekin (/mob/living/carbon/human) @ (the snow) (20,117,6) (/turf/simulated/floor/outdoors/snow/snow/snow2/cryogaia) (ckey=blackangelsace)
   usr.loc: (the snow) (20,117,6) (/turf/simulated/floor/outdoors/snow/snow/snow2/cryogaia)
