### ISSUE TITLE
Mining gets little to no way to Migitate/protect against Radiation

### ISSUE THREAD

**Issue by Dwaggy** [Yawn-Wider/YWPolarisVore#118]
#### Brief overview of the feature
So, its been brought to my attention that radiation blasts from the event, and from accidentally cracking open an artifact, blast you with enough radiation to kill you before you can make it back to the station in many cases.. especially problematic if theres little to no crew/staff on to come pick you up.

#### What you want to happen
For one of two things to perhaps happen:
- The amount of damage the rad blast event causes, and destroying artifacts causes to be lowered to a point where it might cripple someone, but not outright *kill* them.
- Or for mining to have better protection against Rads. Via the form of perhaps buyable radiation voidsuits in the mining vendor, or upping the rad protection of current mining suits, along with having perhaps a supply of anti tox/rad pills. just enough so that if medical isnt operational, they dont have to break in to save their ass quite so much. such that a prepared miner could save their ass long enough to make it back to home base.
 
#### Anything else you may wish to add:
This issue would likely be persistent even if we move maps, and definitely needs some looking at.

**Comment by Hawk-v3** [comment]
Can you put plates into voidsuits to change their protection?

**Comment by Dwaggy** [comment]
Don't believe so. only thing i know of that has the plate changing is the plate carrier armour plating?

**Comment by DeepIndigo** [comment]
Hardsuits are as-is, as far as I'm aware. The only mods you can do to them is air tanks, species reshaping (via suit cycler), and making the helmet/magboots built in. Repairs to them are possible if they get punctured.

**Comment by Dwaggy** [comment]
Just checked, and as of right now, the mining void suits that are available, offer a 20% radiation protection.
Which..when you get blasted by either event, does basically nothing. since whoever coded the events took this in to account apparently and just made it blast so much they will die anyway, making it that miners basically may as well have no protection, for all its worth.
I understand these events are ment to be big 'fuck you, you messed up' style of things. but to outright kill because you happened to dig the wrong tile or be out without a pod because you have to pay for them out of your own points.. *shrug*

**Comment by Hawk-v3** [comment]
That's pretty much bullshit. Sorry, but if there's one thing I hate it's "They've got 20% protection, so lets make the event require 100% so they get fucked over anyway, and let's also validate all the complaints that less than 100% protection is worthless."

That's called "Setting limits on people and then fucking them anyway."

**Comment by Dwaggy** [comment]
Pretty much yeah. I'll be honest im not entirely sure where these events are located in files, and *exactly* how much radiation damage they do.
But they do enough that in 9/10 cases, unless you have the trait that gives you like, 150 health, your as good as dead within minutes. even with the mining suit. And even with the 150 health, chances are your going to be dead too, it'll just take a little longer. but without mining staff preparing by getting chemistry to get anti rad pills and stuff, if either of these 'fun' events hit, chances are they're going to be dead and nobody will ever notice without ooc/meta knowledge of some sort (though thats partly the miners faults for never getting a backup/death implant in the first place. but still.)

**Comment by Hawk-v3** [comment]
It uses https://github.com/Yawn-Wider/YWPolarisVore/blob/master/code/modules/events/solar_storm.dm

So it burns you and radiates you, but it looks like the coding is fucked up as it happens on NOT SPACE TILES. Because that's the colony surface, mining level. I'd assume they used Mining area? But that's an assumption.

**Comment by Dwaggy** [comment]
Yep. The solar storm is a radiation event that hits mining areas specificly. theres another event i think for the space stuff...i think

**Comment by Jonathan-Fort** [comment]
Queued for 1.0 implementation

**Comment by Jonathan-Fort** [comment]
Implemented in 1.0
