### ISSUE TITLE
Allow RPED to swap out beakers.

### ISSUE THREAD

**Issue by Hawk-v3** [Yawn-Wider/YWPolarisVore#133]
#### Brief overview of the feature
The RPED cannot swap out beakers in upgradeable machines.

#### What you want to happen
Allow it to do so.
 
#### Anything else you may wish to add:
Should just be a case of allowing beakers to be in it.

**Comment by Hawk-v3** [comment]
And cells

**Comment by Jonathan-Fort** [comment]
Queued for 1.0 implementation.

**Comment by DeepIndigo** [comment]
This, yes, PLEASE.
