### ISSUE TITLE
Server crashed after stepping into a black tile (dark space?)

### ISSUE THREAD

**Issue by Repede** [Yawn-Wider/YWPolarisVore#138]
#### Brief description of the issue
A player said they saw a dark space in medbay (pitch black tile), and that as soon as they stepped in it the server crashed. (DreamDaemon crash error from the discord bot)

#### What you expected to happen
No crashes

#### What actually happened
Crashes

#### Steps to reproduce
- See dark tile in medbay
- Step on the tile
- Boom

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
No idea why they saw the black tile or anything, it's just a thing they saw. They claim to have DCed the moment they stepped in it (most likely caused by instant server crash)

**Comment by Hawk-v3** [comment]
Do we have any other logs there?

**Comment by Repede** [comment]
Sadly not, nothing showed up on them at all. I'm thinking the Black Tile was seen because stuff was already breaking and the client wasn't given turf info or something
