### ISSUE TITLE
Coloured Pill Bottles

### ISSUE THREAD

**Issue by SnekWithARPG** [Yawn-Wider/YWPolarisVore#145]
#### Brief overview of the feature
Coloured pill bottles are already in game.  There's random spawns in medbay on the tables, and there's a full set of coloured bottles in a Combat Medkit.  Red, yellow, blue, green, grey, _*lighter-grey?*_.  Lighter grey is a **maybe**.  I don't know for sure but I'm certain on the others.  Red for Bicar, Yellow for Kelotane, blue for Dexalin, green for Dylo, grey for Tramadol, lighter-grey for Spaceacillin perhaps.

Looking at Pill Bottle labels can take a decent amount of time, colours could increase the speed at which lobsters stop dying.

See combat medkit for example, has each pill bottle specified Plus an advanced health scanner.
#### What you want to happen
Some way to either colour pill bottles, or a prespawn of each coloured pill bottle within medbay.

**Comment by Hawk-v3** [comment]
Notes for self.
- Colouration can be set for pills, look into those and have to get a spriter to do up a bottle that follows the correct masking, whatever that is, if I can't do it justice myself.
- Open up the chemmaster code, find out how it's making the menus for the pill and bottle selections. Add in NanoUI (ugh) coding for a new clickable box for bottle colour selection, default to orange.

**Comment by TheFurryFeline** [comment]
Didn't https://github.com/PolarisSS13/Polaris/pull/6199 give what this is asking for?
