### ISSUE TITLE
Unchargable computers!

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#166]
#### Brief description of the issue
Tablets and laptops can not be plugged into chargers, giving the "this [computer type] does not have a battery installed" message.

#### What you expected to happen
To plug laptops and tablets into chargers, as in revisions past.

#### What actually happened
Getting no battery installed. so maybe it doesn't recognize the batteries or something?

#### Steps to reproduce
- Spawn with or assemble a laptop or tablet, any battery type.
- Run down the battery some.
- Try to slot it into he little boxy white chargers as one does, and marvel at the confusedjackiechan.jpg that induces.
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 9899ed5a1f6975e361991d269a60b0e210f4174a 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Hawk-v3** [comment]
I'll have to see what they're actually counting as. I suspect they're not being called cells.

**Comment by izac112** [comment]
Charging laptops seems to work fine now
