### ISSUE TITLE
Clear gas masks has noses poking through then

### ISSUE THREAD

**Issue by Trilbyspaceclone** [Yawn-Wider/YWPolarisVore#167]
#### Brief description of the issue
As it turns out wearing a clear gas mask leaves a human nose poking out of it making it look goofy

#### What you expected to happen
For it to not have a nose poking out and making it look bad

#### What actually happened

Made my nose poke out making the outfit I ware look bad
#### Steps to reproduce
- (Step 1) Get a clear mask
- (Step 2) Have a nose
- (Step 3) Ware it
- (Step 4) Cry

#### Code Revision
Server revision:  - 2019-09-19
9899ed5a1f6975e361991d269a60b0e210f4174a 
 
#### Anything else you may wish to add:
Cry a lot

**Comment by Hawk-v3** [comment]
It's either a spriting problem, or a masking problem, if the nose can be hidden.
