### ISSUE TITLE
Fluff broke please restart

### ISSUE THREAD

**Issue by GeneralPantsu** [Yawn-Wider/YWPolarisVore#17]
#### Brief description of the issue
Basically, trying to roll up the sleeves on my fluff item for Samantha Quzix results in the message "You cannot roll up your Mech Pilot Bodysuit's sleeves!" even though it having worked previously perfectly.

#### What you expected to happen
Well, expected it to use the "unzipped" sprite like back before it borked.

#### What actually happened
You cannot roll up your Mech Pilot Bodysuit's sleeves!

#### Steps to reproduce
- (Step 1) Wear suit
- (Step 2) Try to roll it up
- (Step 3) Don't be able to roll it up

#### Code Revision
Server revision:  - 2018-08-18
ddce9af22057a86a104b1b9925e06a9131a1b6a1 
 
#### Anything else you may wish to add:
Doing a bit of digging myself into the .dmi I noticed that the relevant needed sprite, "pilotsuit_r_s" is actually missing. Not I don't really know how to get my grabby paws onto that but older versions of the code should have it? No idea how to get my hands onto those either though...

EDIT: I actually found the DMI on my pc in case it actually is needed!
https://cdn.discordapp.com/attachments/283996406639886336/480862004890828820/mechpilot_dlc__seasonpass.dmi

**Comment by Hawk-v3** [comment]
The older version of the code should have it, yes. Technically the sprite being there shouldn't matter to the code, so I suspect there's two issues mixed together there, or one autocheck somewhere. Do you have the object path for the suit? /obj/item/clothing whatever?

**Comment by GeneralPantsu** [comment]
Oh yeah, wanted to put that bit here too. 

/obj/item/clothing/under/rank/security/corp/fluff/sam_bodysuit
