### ISSUE TITLE
Bad Paperwork Disposal

### ISSUE THREAD

**Issue by ValiantEsp** [Yawn-Wider/YWPolarisVore#178]
When on harm intent, with a crumpled piece of paper, targeting the mouth, you should really be able to feed someone their paperwork.

Currently : Paperwork Head crumples Form into a ball!
You begin to wipe off Target's lipstick.

Preferred : Some oxydamage, 'paper' in stomach reagents.

**Comment by cebutris** [comment]
I'll get right on it
