### ISSUE TITLE
AI Flavortext/ooc notes

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#182]
#### Brief overview of the feature
Basically have the hologram be examine-able, and have it give the flavor text/ooc notes of the AI player's save slot.

#### What you want to happen
See above
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Nope.

**Comment by Hawk-v3** [comment]
Robot flavour works now, apparently, see if it can be applied to the hologram?

**Comment by DeepIndigo** [comment]
I last played a borg and their ooc ntoes don't, but yeah, the robot text on the hologram would be dope
