### ISSUE TITLE
Frontier Phaser ammo issue

### ISSUE THREAD

**Issue by FrostyBeep** [Yawn-Wider/YWPolarisVore#20]
#### Brief description of the issue
Reloading or switching the explorer weapons from 

#### What you expected to happen
10 shots for both the phaser and holdout phaser

#### What actually happened
8 shots for the phaser and 2 for the holdout phaser

#### Steps to reproduce
- Grab a phaser from the exploration shuttle's weapon bay
- Observe the weapon to see its ammo count
- Reload or switch the fire mode to low-power and back to normal
- Observe the weapon to see its ammo count
- Be confused

#### Code Revision
- 2018-08-18 - ddce9af22057a86a104b1b9925e06a9131a1b6a1 
 
#### Anything else you may wish to add:
- I was unable to do any tests on if the 10 shots was accurate, as I wasn't sure about if I should shoot the weapon anywhere indoors or if it would be right to do IC

**Comment by izac112** [comment]
can't speak for the normal phaser part but holdouts are suppose to only shoot 2 shots.

**Comment by FrostyBeep** [comment]
When you examine each of them before shooting, reloading, or changing fire mode, it shows 10 shots regardless of the type. If it should be 8 and 2 for the both of them, then the issue is with it showing 10 to begin with,

**Comment by Hawk-v3** [comment]
Bug has been fixed upstream.
