### ISSUE TITLE
RD hardsuit chestpiece causes lag

### ISSUE THREAD

**Issue by Dropshotz** [Yawn-Wider/YWPolarisVore#208]
#### Brief description of the issue
Title

#### What you expected to happen
No lag like wtf

#### What actually happened
so much lag jfc

#### Steps to reproduce
- get AMI hardsuit
- Enable
- L A G

#### Code Revision
Server revision:  - 2019-10-08
5671a187c3b5fc36c08c6583a79b55344272779d 
#### Anything else you may wish to add:
- as long as the chestpiece is not visible, no lag. So pressing this button here http://prntscr.com/phd4i7 removes the lag, or taking off the chestpiece itself

**Comment by Dropshotz** [comment]
Update: It seems to be a module, currently trying to figure out which

**Comment by Dropshotz** [comment]
Update, it seems to be only this one rig suit I got that is bugging the fuck out.

**Comment by Dropshotz** [comment]
Update! Wearing the suit for long periods of time causes increasing amounts of lag when chest piece icon is visible.

**Comment by Hawk-v3** [comment]
Reading this bug is like an ever increasing galaxybrain meme. No offense intended to droppy, more like, how... How is JUST that Rig suit causing this?

**Comment by Dropshotz** [comment]
I have no idea. I only have experience with the AMI suit. Other suits may cause it too if worn for long enough.

**Comment by Dropshotz** [comment]
http://prntscr.com/phy326

Got some info from a friend on a presumed cause.

**Comment by Hawk-v3** [comment]
Urgh, ok, I'll have a look. See if it's specific to RIGs or just that suit.

**Comment by izac112** [comment]
Closed until someone else mentions having this issue
