### ISSUE TITLE
Cryogaia Atmospheric pressure failure

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#232]
#### Brief description of the issue
Pressure of Cryogaia is way below expected levels, likely due to temperature. Yet Tether's temperature changes don't seem to affect it's pressure levels.

#### What you expected to happen
Temperature to change during weather cold, or warmer, and pressure to stay the same.

#### What actually happened
Pressure drops dramatically due to the cold, causing pressure injuries outside in the snow.

#### Steps to reproduce
- (Step 1)Simply test the main cryogaia outpost
- (Step 2) Walk outside, take note in lack of pressure.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Likely an issue with defines and map's code settings.

**Comment by RadiantFlash7** [comment]
Right. Obvious issue is that the planet temperature is too low to accomodate the pressure, as pressure does not stay constant.
2 fixes: 
A) Reduce temperature freeze, 
B) increase base pressure as temperature won't get very warm to make it over pressured.

**Comment by Repede** [comment]
This is fixed
