### ISSUE TITLE
New Map Mining does not Random gen

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#233]
#### Brief description of the issue
new Map's mineral turfs don't randomly generate, and instead just block fill on the mineral tiles.

#### What you expected to happen
Areas selected as undiscovered area in mining to have their mineral tiles randomly built

#### What actually happened
Minerals are placed in every spot with a mineral turf. Xenoarch and minerals are still generated in the rock.

#### Steps to reproduce
- (Step 1)Boot up the map, 
- (Step 2)Look at mining
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Possibly coding/mapping issue, Don't know whats up with this one.

**Comment by Repede** [comment]
Fixed
