### ISSUE TITLE
Infinite Metal

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#236]
#### Brief description of the issue
You can create infinite metal.

#### What you expected to happen
Not to be able to create infinite metal.

#### What actually happened
I could.

#### Steps to reproduce
1) Get at least 2 metal. Construct an APC frame.
2) Use in-hand, and select a random frame to change it to.
3) Deconstruct for more metal than you put in.

#### Code Revision
34ee47bf6d9f0211640943aa6b36739babb12b8c

**Comment by Jonathan-Fort** [comment]
This appears to be an upstream issue.

**Comment by TheFurryFeline** [comment]
S'posedly fixed with https://github.com/PolarisSS13/Polaris/pull/6085

**Comment by Shadow-Quill** [comment]
That PR was from April. Issue still exists.

**Comment by izac112** [comment]
@Shadow-Quill is this still an issue?

**Comment by Shadow-Quill** [comment]
Yep, just confirmed it.

**Comment by izac112** [comment]
Does not seem to be an issue anymore
