### ISSUE TITLE
Revert to old command reports

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#238]
#### Brief overview of the feature
Change back to Old Central command Report's.
Providing much easier time differientating from standard radio chatter

#### What you want to happen
Old Centcom reports were in black text, with a red header, larger then radio chatter and stood out.
Change the command report back to this.

 
#### Anything else you may wish to add:
I believe it's just a code issue. Might be as simple as copypastaing the old code if that still works.
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
Was discussed and is not getting changed back

**Comment by RadiantFlash7** [comment]
</3
