### ISSUE TITLE
Chemavator can't have stuff thrown into it

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#277]
#### Brief description of the issue
You cannot throw stuff into chemivators (mayb other smartfridges?) and stock them.

#### What you expected to happen
The item to get stocked.

#### What actually happened
It fell to the floor.

#### Steps to reproduce
1) Find chemivator.
2) Yeet item into it.
3) Cry as it falls to the ground and spills your milk.

#### Code Revision
ab6a36db6d8ef6b0e00b6097452bf2c59f8e884c
 
#### Anything else you may wish to add:
I'm not 100% if it works/doesn't work for other smartfridges.

**Comment by izac112** [comment]
your supposed to be able to "throw" them in ?

**Comment by Shadow-Quill** [comment]
https://github.com/Yawn-Wider/YWPolarisVore/blob/master/code/modules/food/kitchen/smartfridge_vr.dm

**Comment by izac112** [comment]
That has never worked on here as far as i am aware

**Comment by izac112** [comment]
Might want to make a issue on vore's git seeing as its their code and has not been touched since 2018

**Comment by Shadow-Quill** [comment]
👍 
https://github.com/VOREStation/VOREStation/issues/6269
