### ISSUE TITLE
Janihound Borgi sprite MIA

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#291]
#### Brief description of the issue
Janihound Borgi Sprite does not appear when selected by janihound.

#### What you expected to happen
Janihoud sprite to change to janiborgi sprite.

#### What actually happened
No sprite appeared. Invisibile hound.

#### Steps to reproduce
- (Step 1)Play Janihound
- (Step 2)Select janiborg sprite

**Comment by izac112** [comment]
Hound is working for janiborg
