### ISSUE TITLE
Mining Airlock to Outside not working

### ISSUE THREAD

**Issue by maxzimusviii** [Yawn-Wider/YWPolarisVore#294]
#### Brief description of the bug
Mining Airlock does not open. I have mining access as a Drill Tech, also had a normal Shaft-Miner ID try, does not open.

#### What you expected to happen
Walk up to airlock controller... press button, door open.

#### What actually happened
Walk up to airlock controller... press button, door NO open.

#### Steps to reproduce
- Walk up to airlock controller
- Try to open door

#### Code Revision
- 222bda04b9502547248f927f07db91d8ed28e6b0 
 
#### Anything else you may wish to add:
- Access issue, or doors are not setup properly. New map, so bugs are expected!

**Comment by RadiantFlash7** [comment]
Fixed!
