### ISSUE TITLE
[Cryogaia] AI loses connection to shells when they go through the elevator

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#297]
#### Brief description of the issue
AI gets kicked out of their shell when going through the elevator. Loses connection @ transit floor.

#### What you expected to happen
To stay connected.

#### What actually happened
Didn't.

#### Steps to reproduce
1) Be AI in shell.
2) Take elevator to a floor.
3) Lose connection at transit floor.

#### Code Revision
222bda04b9502547248f927f07db91d8ed28e6b0 
 
#### Anything else you may wish to add:
Elevator.

**Comment by RadiantFlash7** [comment]
Added Transit to AI levels in defines. I think that'll fix it.

**Comment by RadiantFlash7** [comment]
Is this still happening?

**Comment by RadiantFlash7** [comment]
No longer happening, Definitely fixed.
