### ISSUE TITLE
One-way windows in security interrogation are backwards.

### ISSUE THREAD

**Issue by IgnusVam** [Yawn-Wider/YWPolarisVore#299]
#### Brief description of the issue
One-way windows in security are backwards.

#### What you expected to happen
People interrogated could not see who was watching them, and reviewers could watch the interview quietly.

#### What actually happened
Watching can't see anything, but the one being interrogated can see into their room.

#### Steps to reproduce
- Walk into both rooms. Compare what you can/can't see.

#### Code Revision
Server revision:  - 2019-12-14
222bda04b9502547248f927f07db91d8ed28e6b0 
 
#### Anything else you may wish to add:
- In the security interrogation area.

**Comment by RadiantFlash7** [comment]
Removed windows and tables entirely. Added walls instead.
