### ISSUE TITLE
Auto-Hiss resets on client restart.

### ISSUE THREAD

**Issue by FrostyBeep** [Yawn-Wider/YWPolarisVore#30]
#### Brief description of the issue
Auto-hiss, no matter the setting, will make itself back to NONE when Dream Seeker is closed and reopened.

#### What you expected to happen
My Auto-hiss setting would remain as I intended

#### What actually happened
It didn't 😛 

#### Steps to reproduce
- Join as Unathi or Tajaran (or anything, but the change is more noticeable)
- Change Auto-Hiss to BASIC or FULL
- Speak and see the rolled R's or pronounced Esses
- Close client
- Reopen client
- Witness it being trash again

#### Code Revision
- 77922ca9e750c48bb3c1cb67c1bc3a0810fc3535
 
#### Anything else you may wish to add:
- I just wanna play my characters as lore-friendly as possible ☹️

**Comment by Hawk-v3** [comment]
Sorry, you're gonna have to remember that one. I'm nowhere near good enough to make this enhancement of tracking client state after a client DCs.
