### ISSUE TITLE
[Cryogaia] Engineering hallway airlock has an air alarm.

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#301]
#### Brief description of the issue
Causes the shutters to close down when someone exits via airlock.

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/44811257/70856374-0aeb9280-1ea1-11ea-98e7-bed5ca2358ef.png)

**Comment by RadiantFlash7** [comment]
Fixed by removal.
