### ISSUE TITLE
[Cryogaia] Exploration/Pathfinder doesn't have cockpit access

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#306]
![image](https://user-images.githubusercontent.com/44811257/70856447-eee8f080-1ea2-11ea-99a0-9c3817c85be5.png)

**Comment by RadiantFlash7** [comment]
Wat. All crew have access here.

**Comment by RadiantFlash7** [comment]
ALl. Not supposed to. Access req's added. Fixed.
