### ISSUE TITLE
[Cryogaia] External security outpost airlock not working

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#311]
#### Brief description of the issue
External airlock at security outpost not opening via controller.

![image](https://user-images.githubusercontent.com/44811257/70856599-530cb400-1ea5-11ea-8637-429fce473046.png)

**Comment by RadiantFlash7** [comment]
Fixed I think.

**Comment by RadiantFlash7** [comment]
Not fixed. Refer to monastary issue. Likely have to replace the airlock door and start it from scratch.

**Comment by RadiantFlash7** [comment]
Might have got it this time.
