### ISSUE TITLE
[Cryogaia] Security airlock non-functional

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#312]
#### Brief description of the issue
Doesn't work at all.

![image](https://user-images.githubusercontent.com/44811257/70856647-260cd100-1ea6-11ea-9e34-98e82a5c221e.png)

**Comment by RadiantFlash7** [comment]
Possibly fixed. Needs testing.

**Comment by RadiantFlash7** [comment]
Definitely fixed.
