### ISSUE TITLE
[Cryogaia] Lockeroom airlock internal door non-functional.

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#316]
![image](https://user-images.githubusercontent.com/44811257/70856844-6e79be00-1ea9-11ea-8173-01d20ab9b32c.png)

**Comment by RadiantFlash7** [comment]
fixed. I think Needs testing.

**Comment by RadiantFlash7** [comment]
Finally fixed this 2 days ago. Everything was how it was supposed to be but it wouldn’t work. I deleted the instance and did the exact same thing, and now it works.
Heck if I know why it didn’t prior.
