### ISSUE TITLE
[Cryogaia] Computers do not have Network

### ISSUE THREAD

**Issue by Repede** [Yawn-Wider/YWPolarisVore#324]
#### Brief description of the issue
Computers (Tablets/Laptops) Have no NTNet connection (Missing relay? Computer servers?)

#### What you expected to happen
To be able to use the computers/download software in the station

#### What actually happened
The tablet computer's screen shows "NETWORK ERROR - Unable to connect to NTNet. Please retry. If problem persists contact your system administrator." warning.

#### Steps to reproduce
Get computer
Try to install software
Failure

#### Code Revision
222bda04b9502547248f927f07db91d8ed28e6b0

**Comment by RadiantFlash7** [comment]
Yeah I got no idea whats up with this.

**Comment by Dwaggy** [comment]
After some quick looking around and curiosity
i have found the issue. Telecomms is missing an NTnet relay
object path at: /obj/machinery/ntnet_relay
The moment i spawned one in, it connected and hooked up the laptops net.
Not sure if it'll need special config in vars to make sure it does the right z-levels. but.. thats the missing componant, at least.

**Comment by TheFurryFeline** [comment]
That sounds about right.

**Comment by RadiantFlash7** [comment]
This was long since fixed.
