### ISSUE TITLE
[Cryogaia] Emergency Cold Apparel on sub1 not connected

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#325]
APC not connected to the grid.
![image](https://user-images.githubusercontent.com/44811257/70857317-c1f00a00-1eb1-11ea-996c-1a03f688e94d.png)

**Comment by RadiantFlash7** [comment]
Just Fixed. It's a bad coded wire, same sort thats been giving me grief throughout map making, where it sends powere differantly then what the sprite show it as.
