### ISSUE TITLE
[Cryogaia] CMO Does not start with combat defib

### ISSUE THREAD

**Issue by Repede** [Yawn-Wider/YWPolarisVore#336]
#### Brief description of the issue
CMO Usually spawns with a combat defib in their closet but it is not here on Cryogaia.

**Comment by RadiantFlash7** [comment]
They do not. The Combat defib starts in the Paramedic storage area on Tetherrrr.

**Comment by RadiantFlash7** [comment]
Well, Despite it not being in the map on the tether, I'll toss a second one in their locker I guess
