### ISSUE TITLE
[Cryogaia] Telecomms have atmos issues causing the servers to shut down.

### ISSUE THREAD

**Issue by Repede** [Yawn-Wider/YWPolarisVore#338]
#### Brief description of the issue
Telecomms should be a closed atmos loop with a cooling machine. Right now it cools the air before dumping it into the waste atmos pipes. There are broken pipes so no air goes into Telecomms. And Telecomms server room is missing a air alarm.

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/5666820/70858756-24f39800-1ed6-11ea-91db-fc527ef87fac.png)

**Comment by RadiantFlash7** [comment]
Repiped it to be better... I think. Maybe. Pending testing.

**Comment by Repede** [comment]
Only issue is the air alarm triggering and shutting off the vents on round start now. Otherwise it seems to be holding?

**Comment by RadiantFlash7** [comment]
Fixeeed.
