### ISSUE TITLE
Missing intercomms and holopads, a list, as requested by the Flasho. Also notes of cam coverage issues.

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#339]
#### Missing holopads
A few of these places are also missing intercoms.
- Medbay reception
- Medbay "Primary Hall" (treatment floor with the sleepers and such)
- Docking Lounge
- Bridge
- Command Meeting Room
- BSG Office
- HoP Office
- Security Processing
- Security Lobby
- Cargo lobby (the halls connected to it are completely blind cam-wise)
- Cargo office
- Primary Tool Storage
- Psych office
- Resleeving Lab
- RD Office
- Research Firing Range
- Medbay Exam room
- AI Foyer, Cyborg Station, and Message server chambers
- Pool
- Fitness room
- Telecomms Control Room (T-comms central chamber APC and air alarm are out of cam coverage and can not be operated, turret hall has no cam coverage, period)
- Tcomms foyer
- Lockerroom (by the shortrange teleporters, this area also has huge blindspots despite being public)
- Gateway Prep
- Engineering Primary Hallway (perhaps by the lockers?)
- Circuit workshop
- Security outpost (blindspot in its airlock)
- Explorer Meeting Room (No cam coverage in the hangar or the hall leading to it)
- Cryogenic Storage and the dining area outside it. (both also have camera issues.)
- Hydroponics (also seems to lack cameras)
#### Possible missing holopads
(These rest in massive blindspots where there is no camera coverage)
- Bar
- Ktichen
- The large public area outside the bridge. (which is around 90% blindspot)
- Cargo (the lumberjack prep area, around 50% is blindspot, door is erroneously labeled "warehouse")

####Other
- Pathfinder office lacks fax machine.
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 222bda04b9502547248f927f07db91d8ed28e6b0 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I may come back to add to this, but these are the immediately apparent ones.

**Comment by RadiantFlash7** [comment]
Much Appreciated. I'll start looking at this tomorrow ^^

**Comment by Shadow-Quill** [comment]
As well as the phoronics lab

**Comment by SplinterGP** [comment]
Places i found problems with cam coverage: 

-  Outside elevator in underground 2

- The hallway in Toxins research on underground 2

- Evacuation, has NO cameras

- Hallway That leads to dorms is massively out of coverage

- Chapel Office door is not covered in camera and chapel desk has no coverage either

- Hallway with Hotsprings outside north library entrance

- Library backroom (private study) has no cameras (no idea if intentional or not)

- Delivery office (has no cameras)

- Most exploration too, only has coverage in pathfinder office and above it, and some small bit of the hangar

**Comment by RadiantFlash7** [comment]
Right Everything on this list is done now. Library backroom does not get a camera, however.

**Comment by Dwaggy** [comment]
More locations without intercomms:
None of the bridge/command locations have any wall intercomms at all.
Bridge, command meeting room, nor BSG office, not CD office, Nor HoP or the hallway.

BSG office is also missing a camera. Given its a room that contains weaponary and gear, coverage should at least be partial there perhaps?

**Comment by DeepIndigo** [comment]
Added a note about the PF fax machine missing

**Comment by TheFurryFeline** [comment]
Throwback to my days of dealing with blindspots as well as cameras placed on same tiles as lightbulbs. Insert Angry Mapper screaming meme.
