### ISSUE TITLE
Insekt for Crisis Borg is broken

### ISSUE THREAD

**Issue by FrostyBeep** [Yawn-Wider/YWPolarisVore#34]
#### Brief description of the issue
The Insekt skin for the Crisis borg is broken and invisible

#### What you expected to happen
A badass skin called Insekt to be my playable character

#### What actually happened
My character skin was invisible

#### Steps to reproduce
- Spawn as a cyborg/android/robot
- Choose crisis as your specialization
- Choose insekt as your skin

#### Code Revision
- 2018-10-04 c13d87a06b97b7417eb8f8e06647e644cefc21bf 
 
#### Anything else you may wish to add:
- literally nothing is visible lol

**Comment by Hawk-v3** [comment]
What does the Insekt skin *look* like?

**Comment by Hawk-v3** [comment]
![image](https://user-images.githubusercontent.com/1232355/46586390-a69b9a80-ca75-11e8-87bb-66a852f4835f.png)
![image](https://user-images.githubusercontent.com/1232355/46586396-b5824d00-ca75-11e8-9ed6-5332be93d80e.png)


Something else? I can't find it where I'd expect the sprites to be.

**Comment by FrostyBeep** [comment]
In-game, it looks like I set my ghost skin to Clear.

**Comment by Hawk-v3** [comment]
What was it MEANT to look like? It was either deleted or name-changed and I can't find out which.

**Comment by FrostyBeep** [comment]
I literally have no idea. I'll try spawning as a different borg type, but I dont know what it _should_ work with.

**Comment by Hawk-v3** [comment]
Right, I cannot find any Insekt sprite in the files. I don't know what it is or what it was meant to be. I'll trim those options.

**Comment by Hawk-v3** [comment]
See upcoming pull.
