### ISSUE TITLE
Impossible to construct a chem master

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#347]
It really is.

**Comment by RadiantFlash7** [comment]
This is a map issue?

**Comment by Shadow-Quill** [comment]
Blame @Repede ಠ_ಠ

**Comment by TheFurryFeline** [comment]
I think this is intentional since ChemMasters are usually for medical to use. But if ya want it constructible, add a new circuitboard and set the frame type to be a machine, at minimum.

**Comment by TheFurryFeline** [comment]
Pfft, that's weird that those PRs didn't automatically close this one. F.

**Comment by Shadow-Quill** [comment]
prolly need write access or something

**Comment by TheFurryFeline** [comment]
Might be it, yeah.
