### ISSUE TITLE
Wiring Issues at the SMES units

### ISSUE THREAD

**Issue by NESgamer190** [Yawn-Wider/YWPolarisVore#348]
#### Brief description of the issue
The wiring is incomplete within a few department SMES rooms.

#### What you expected to happen
Said SMES' to recharge properly.

#### What actually happened
No power charge

#### Steps to reproduce
1:  Set the SMES units to gather power
2:  See them NOT gain any power
3:  Despair

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- SMES 1:  Research (Breaker box)
- SMES 2:  Xenobiology and Toxins (Under SMES)
- SMES 3:  Archaeology (Also Under SMES)

**Comment by RadiantFlash7** [comment]
What the actual heck I was thinking in research. Uh... fixed now.

**Comment by RadiantFlash7** [comment]
Fixed entirely.
