### ISSUE TITLE
[Cryogaia] Rouge drone event active

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#350]

**Comment by RadiantFlash7** [comment]
Debating leaving this in with minor changes actually. Rogue Security drones showing up would be neat, though, maybe not inside the outpost walls.

**Comment by TheFurryFeline** [comment]
As the code currently stands, they will spawn where you have landmarks labelled for carps to spawn at and if the drone event is in the list of events possible for a shift.

**Comment by RadiantFlash7** [comment]
Event info shifted to reflect new map. Rogue drones are stayin'.
