### ISSUE TITLE
[Cryogaia] Rain weather causes pressure fuckery (everyone falls down and cannot get up)

### ISSUE THREAD

**Issue by Repede** [Yawn-Wider/YWPolarisVore#352]
#### Brief description of the issue
Rain probably changes the temperature too much, which makes the pressure vastly different from the usual, and therefore makes everyone fall down from 'rush of air knocks you over' and cannot get up at all.

#### What you expected to happen
People to be able to stand in the rain without falling over.

#### What actually happened
Wind knocks over

**Comment by RadiantFlash7** [comment]
Yeah uh, Thats not the reason that happened. Gotta look into this, but I suspect the cargo shuttle causing space tiles may be responsible.

**Comment by RadiantFlash7** [comment]
I fixed the issue with the space shuttle tiles that might've been causing this? No issues reported since. Gonna give it two more days and close.

**Comment by RadiantFlash7** [comment]
This hasn’t happened again since this one instance, and it’s definitely not caused by the rain. I’ll keep an eye out for this again, but for now I’m assuming fixed.
