### ISSUE TITLE
[Cryogaia] Virology's Pathogen Vault Bolts don't unbolt.

### ISSUE THREAD

**Issue by Championfire** [Yawn-Wider/YWPolarisVore#356]
#### Brief description of the issue
The button used for unbolting and bolting Virology's pathogen vault doesn't unbolt the doors when pressed.

#### What you expected to happen
The bolts to unbolt.

#### What actually happened
Bolts didn't unbolt, even with usage of ID in the hand.

#### Steps to reproduce
- Press button
- Watch as it doesn't unbolt

#### Code Revision
 Server revision:  - 2019-12-15
f914803532654806fc0004d85a937c6c5c86bcc3

**Comment by RadiantFlash7** [comment]
uuuh. I don't quite know why this isn't working.
ID Is the same. Might be the type of button I think?

**Comment by RadiantFlash7** [comment]
AHAH. Special function variable was set incorrectly. Toggling bolts ins function 4.
