### ISSUE TITLE
no Firelocks in the Evacuation corridor

### ISSUE THREAD

**Issue by SplinterGP** [Yawn-Wider/YWPolarisVore#360]
#### Brief description of the issue
Needs a firelock in the two doors in evac

#### What you expected to happen
To have a firelock between the two areas, since they are different areas and all

#### What actually happened
Has no firelock

#### Steps to reproduce
- Turn one of their fire alarms
- No firelocks goes up

#### Code Revision
- Server revision:  - 2019-12-17
f47d1dc4a131abb0613b3cf6e31efbe60bb39ca3 
 
#### Anything else you may wish to add:
-Evacuation
![image](https://user-images.githubusercontent.com/29824735/71039895-070b7a80-2104-11ea-98d8-8a20d725091e.png)

**Comment by RadiantFlash7** [comment]
Fixed.
