### ISSUE TITLE
Heckin debris field away mission isn't adjusted for larger map size. 

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#364]
#### Brief description of the issue
Step teleporters in debris field away mission have not been adjusted for the 250x250 map.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
Gonna fix dis by changing the map itself to 250x250 and letting the thing work out as it should with a  proper area.

**Comment by RadiantFlash7** [comment]
Adjusted for 250x250, Need to double check teleporters to ensure it works fine.

**Comment by RadiantFlash7** [comment]
I think it's working so far.

**Comment by RadiantFlash7** [comment]
Exploration shuttle airlock is so horribly borked, Anyone trying to use this zone spaces the shuttle entirely. Have not been able to successfully test this.

**Comment by Repede** [comment]
Fixed in master with the new shuttle
