### ISSUE TITLE
Bishop FPBs melt in normal atmos

### ISSUE THREAD

**Issue by Cairo283** [Yawn-Wider/YWPolarisVore#365]
#### Brief description of the issue
Now I'm not sure if this happens to other kinds of FPB parts, since I heard that another FPB that uses different parts is fine, but Bishop parts will endlessly take damage without a suit cooling unit, even if you are not wearing a suit and are in normal atmosphere.

#### What you expected to happen
For me not to become the Wicked Witch of the West when joining a round.

#### What actually happened
I'M MELTING OH GOD OH FUCK

#### Steps to reproduce
- (Step 1) Set your character to be an FPB with Bishop parts
- (Step 2) Join the round
- (and so on)

#### Code Revision
- 42a888dfd8eceab058d97d00c2a24baa0663d822 
 
#### Anything else you may wish to add:
- It doesn't matter if you are naked, as well. You will always melt.

**Comment by Cairo283** [comment]
Looks like Unbranded melts as well.

Going to go through a few different bodies and see what else is gooched.

**Comment by Cairo283** [comment]
Alright I've tried a huncha-buncha different bodies, and I melt no matter what. No idea what's going on.

**Comment by RadiantFlash7** [comment]
Seemingly, still a problem, I believe. I'm not sure whats causing it, or where to look.

**Comment by izac112** [comment]
Probably has something to do with the temperature modifications we did to a lot of species, but not 100% on that
