### ISSUE TITLE
[Cryogaia] Lack of Secure Disposals for Virology

### ISSUE THREAD

**Issue by Championfire** [Yawn-Wider/YWPolarisVore#366]
#### Brief description of the issue
The virology disposals unit, despite the hazard marking, does not go to a secure spot, or at least, goes to where it potentially could cause infection to crewmembers working in cargo.

#### What you expected to happen
Disposals to be safe and not risk crew contact for virology's disposals unit.

#### What actually happened
Disposals unit sent the contaminated materials to the cargo belt. Cargo crewmember nearly came in contact with a monkey disease carrier that was sent down disposals, and was not infected due to luck. This is a risk that shouldn't be taken.

#### Steps to reproduce
- Send thing down marked and presumed secure disposals route
- Ask Cargo staff
- See monkey and other infected individuals come up on the belt and risk infection and outbreak of disease.
- Cry.

#### Code Revision
- Server revision:  - 2019-12-18
42a888dfd8eceab058d97d00c2a24baa0663d822 
 
#### Anything else you may wish to add:
- While it's not mapped, it should be. Even if it's not intended to be secure, the hazard markings around it make no sense due to the lack of any other unit having said 'warning' lines in any other department. It's a health and safety risk from an ingame standpoint, and a risk in general. Bap me if it's already done and I didn't see it. I was recommended to post this as an issue.

**Comment by RadiantFlash7** [comment]
Added a sealed maint room for this. ...Don't fall down that disposals chute.
