### ISSUE TITLE
[Cryogaia] Organ Printer Path Error

### ISSUE THREAD

**Issue by Legion2552** [Yawn-Wider/YWPolarisVore#367]
#### Brief description of the issue
The organ printer is the wrong one. It doesn't allow Biomass to be added. It's the base path for the machine. The one in is
/obj/machinery/organ_printer

when it needs to be
/obj/machinery/organ_printer/flesh

#### What you expected to happen
The Organ Printer to actually take biomass and print organs.

#### What actually happened
It doesn't.

#### Steps to reproduce
- Delete organ printer.
- Replace with /obj/machinery/organ_printer/flesh
- It now works as intended.
- (and so on)

#### Code Revision
- 42a888dfd8eceab058d97d00c2a24baa0663d822 

#### Anything else you may wish to add:
- ![image](https://user-images.githubusercontent.com/59037744/71139406-13630680-21dc-11ea-9292-29a218a14176.png)

**Comment by RadiantFlash7** [comment]
Fixed.
