### ISSUE TITLE
[Cryogaia] Virologist doesn't have access to the pathogen vault.

### ISSUE THREAD

**Issue by Championfire** [Yawn-Wider/YWPolarisVore#368]
#### Brief description of the issue
Virologists don't have access to the doors to the virology pathogen vault.

#### What you expected to happen
Door to open with access.

#### What actually happened
Didn't open. Let me in. Let me iiiiin.

#### Steps to reproduce
- unbolt door
- door doesn't open

#### Code Revision
Server revision:  - 2019-12-18
42a888dfd8eceab058d97d00c2a24baa0663d822 
 
#### Anything else you may wish to add:
- N/A

**Comment by RadiantFlash7** [comment]
Fixed.
