### ISSUE TITLE
[Cryogaia] XenoArcheology Exterior Doors Access Wrong

### ISSUE THREAD

**Issue by Legion2552** [Yawn-Wider/YWPolarisVore#369]
#### Brief description of the issue
The Xeno Archeology Doors have Mining Access requirements, not XenoArcheology/Science Access.

#### What you expected to happen
The XenoArcheologists to be able to open them.

#### What actually happened
They cannot. I spawned a pleb and gave him a Science ID and a Mining ID. The Mining ID opened the door.

#### Steps to reproduce
- Attempt to open as a Scientist.
- You cannot.
- Attempt to open as a Miner
- You can.

#### Code Revision
- Server revision:  - 2019-12-18
42a888dfd8eceab058d97d00c2a24baa0663d822 

 
#### Anything else you may wish to add:
- 
![image](https://user-images.githubusercontent.com/59037744/71204959-6508a100-226f-11ea-9118-4a062a1b2e1b.png)

**Comment by RadiantFlash7** [comment]
Fixed.
