### ISSUE TITLE
Atmospherics Waste to space intersection goes nowhere fast.

### ISSUE THREAD

**Issue by NESgamer190** [Yawn-Wider/YWPolarisVore#377]
#### Brief description of the issue
As the title explains, the atmospherics manifold that allows waste gases to go to 'space' follows some pipes, before dead-ending somewhere inaccessible.

#### What you expected to happen
To be able to vent some unsalvagable gases to the atmosphere of the surface

#### What actually happened
Nowhere to vent the stuff from waste to surface.

#### Steps to reproduce
N/A

#### Code Revision
N/A
 
#### Anything else you may wish to add:
Should be a fairly easy fix to have a vent on the surface, along with a couple pipes to transfer from atmospherics to the surface near the supermatter.

![Atmos mishap](https://user-images.githubusercontent.com/58912216/71313746-f6604a80-240a-11ea-9653-2ee5f40dfceb.png)

**Comment by RadiantFlash7** [comment]
Now properly vents to Above atmosphere.
