### ISSUE TITLE
Xenoflora ideas/fixes

### ISSUE THREAD

**Issue by Liu-Junior** [Yawn-Wider/YWPolarisVore#378]
#### Brief overview of the feature
- Xenoflora's "Isolation" trays are out in the open. Maybe add a glass wall to atleast actually isolate them.
- Xenoflora's pipes from Isolation to "waste" currently leads to... Uh, nowhere. Maybe connect them to some kind of atmos system? 
- Xenoflora's Containment room is currently too small for any kind of efficient modifications to the piping for Exotic seeds' needs. It'd be great to have more space for it.

#### What you want to happen
A glass box for Xenoflora's "isolation". An actual Waste for Isolation's piping. More space for containment.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
"Isolation": https://gyazo.com/76581d32615cb799c8ec8d8eee57e339
Isolation to "waste": https://gyazo.com/bae1fd1114d892c84013c878a6fde852
Xenoflora Containment: https://gyazo.com/4040cb961587cf1e3260d324000e8a6d

**Comment by izac112** [comment]
As for the trays you can right click them to put a glass over the tray to isolate them, though nice on spotting the issue with the unconnected pipe and yeah that room probably should be a bit bigger

**Comment by RadiantFlash7** [comment]
This was fixed, ages ago. I never closed the issue. Whoops.
