### ISSUE TITLE
More bogus wires and APCS.

### ISSUE THREAD

**Issue by NESgamer190** [Yawn-Wider/YWPolarisVore#395]
#### Brief description of the issue
A couple wires on station happen to still be a bum deal, along with a double APC at the Research Outpost Gas Mixing area.

#### What you expected to happen
All wires to be nominal, and only 1 APC for the Research Outpost Gas Mixing area.

#### What actually happened
The wire just north of the APC in emergency EVA is registered on the multitool as not being connected, as is the wire knob at the solars to station connection.  Also, two APCs in the Research Outpost Gas Mixing.

#### Steps to reproduce
N/A

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Double APC issue at Research Outpost Gas Mixing:
![image](https://user-images.githubusercontent.com/58912216/71538894-08595600-2901-11ea-9b86-96c6192cd13a.png)
Bogus wire at Solars:
![image](https://user-images.githubusercontent.com/58912216/71538914-58381d00-2901-11ea-92f2-3c3ed37e8aec.png)
Bogus wire at Emergency EVA
![image](https://user-images.githubusercontent.com/58912216/71538924-a2210300-2901-11ea-9b01-7ebb73d019e0.png)

**Comment by RadiantFlash7** [comment]
Apc fixed, i rewired eva to work.
I need to test out the solars, I was under the impression their working.

**Comment by RadiantFlash7** [comment]
Fixed in Dev build.
