### ISSUE TITLE
Security Hallway Camera Not On Wall

### ISSUE THREAD

**Issue by TinnCatt** [Yawn-Wider/YWPolarisVore#399]
#### Brief description of the issue
A little sprite issue. The wrong direction was used and this camera is floating and facing the wrong direction. 

#### What you expected to happen
For it to be on the wall!

#### What actually happened
It's in the wrong direction and floating!

#### Steps to reproduce
N/A

#### Code Revision
28/12/2019
987520771335d558581eba695c1d9eda0b05b03d 

(Been around for awhile though)
 
#### Anything else you may wish to add:
Screenshots: 
![Camera](https://user-images.githubusercontent.com/35948390/71547779-7427d700-2972-11ea-86a9-0dcf41251361.PNG)
![SecurityCamera](https://user-images.githubusercontent.com/35948390/71547782-79852180-2972-11ea-8826-c1c781bd172f.PNG)

**Comment by RadiantFlash7** [comment]
Fixed in dev.
