### ISSUE TITLE
[Cryogaia] Misnamed SMES'

### ISSUE THREAD

**Issue by Crystal9156** [Yawn-Wider/YWPolarisVore#407]
#### Brief description of the bug
Lower Civilian SMES is correctly named on its bypass, however its SMES is simply named "Substation - Civilian" whereas the Surface Civilian SMES is properly if differently named "Upper Civilian Substation Bypass" and "Substation - Surface Civilian"

#### What you expected to happen
SMES' to be named matching with their bypass and labeled properly

#### What actually happened
Not the thing above

#### Steps to reproduce
Go on RCON
Look at SMES names
Cry at Naming Scheme
Repeat

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
Server revision:  - 2019-12-30
2bd76446a5aa97660d26a696001c8049d7f7c56e  

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
Fixed in dev build.
