### ISSUE TITLE
Item manipulation trough smaller containers

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#411]
#### Brief overview of the feature
You can open your bag, then open your emergency box inside your bag, and grab your item such as a breath mask, without having to pull your box out. You can interact with that box's inventory while it's in your bag. This would apply for a tool belt currently in your bag rather than in your belt slot, too. It would also apply to a smaller, and smaller yet container, such as a syringe case inside a carboard box inside your backpack. All you have to do it to open that container by clic+drag it to your character's sprite, and you can put or take items from that storage.

#### What you want to happen
Currently, you can only put items trough a second container, but you cannot take anything back, and it forces you to grab out that container in one hand, then to switch hand, then open your box again.

I'd like to be able to immediately take back and forth from my containers without having to pull them out of my bag constantly.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
That is for balance reasons
