### ISSUE TITLE
Rapide Construction Device Quality of Life

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#412]
#### Brief overview of the feature
You can easily make your RPD drop down a stack of components inside, namely a stack of micro-manipulators you just replaced trough a round of upgrades within the station. You can easily dump them out, namely into an autolathe to recycle them into metal and glass.

#### What you want to happen
Currently, you have to slowly dump out every single obsolete component out of the RPD by hand, and then handle them into the autolathe, one by one.  I'd like to be able to dump all of them to the recycling easily instead.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
This isn't the RCD but rather the RPD. Names a little incorrect :P
