### ISSUE TITLE
Synths will burn up out of seemingly nowhere

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#413]
#### Brief description of the issue
Some synth human would spontaneously start to take constant, massive amounts of burn damage.

On one instance, I assembled an full body of prosthetic, then inserted a player-controlled positronic cube in it. From the moment it stood awake and up on it's legs, it would take burn damage. It'd scorch it's face to a tangled mess in a matter of seconds, it'd cripple and die, just existing.

On a second instance, a synth player simply spawned at the arrival shuttle and immediately took massive burn damage. They were cryo'd after they called for help, still burning up.

#### What you expected to happen
For them to not burn up out of nowhere.

#### What actually happened
They died.

#### Steps to reproduce
- (Step 1) : make a human chassis at robotics
- (Step 2) : insert a player-controlled positronic cube
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Hawk-v3** [comment]
#365

**Comment by izac112** [comment]
#792
