### ISSUE TITLE
[Cryogaia] Xenoflora oddities

### ISSUE THREAD

**Issue by cebutris** [Yawn-Wider/YWPolarisVore#415]
#### Brief description of the issue
Xenobotanists (and presumably xenobiologists) do not have access to this door in research
![image](https://user-images.githubusercontent.com/26630607/71650577-dcfdaf00-2ce4-11ea-9526-74d0b147b70f.png)
even though they have access to the door marked in blue, and there's a quick way around
![image](https://user-images.githubusercontent.com/26630607/71650610-146c5b80-2ce5-11ea-993f-3689a2f350d9.png)
it's strange that they can access one side of the room but not the other

Additionally, there's no botanist lockers in Xenoflora, as there were on the Tether. This may have been an intentional design choice, but it was convinient for all the botany gear to be in one place instead of spread around in multiple places. As well, they have service headsets, which can help a xenobotanist coordinate with the kitchen/bar if there's no real botany.

#### What you expected to happen
The marked door to open

Botany lockers to be present in Xenoflora

#### What actually happened
The marked door does not open

Botany lockers are not present in Xenoflora

**Comment by RadiantFlash7** [comment]
Admittedly, the lack of a botany locker was intentional, however, the door is a bit of an oversight.

**Comment by cebutris** [comment]
I don't agree with the lack of the botany locker- The only botany tools Xenoflora really gets is what's in the vendors, plus a single plant scanner and a single hoe. They don't get any gloves (which is important since plants can mutate spines), or a hand shovel for digging up plants, or anything else.

Though it's not a _huge_ deal and not a hill I'm going to die on if you don't think they need it

**Comment by RadiantFlash7** [comment]
Can add gloves, and some more tools in a crate. But botany lockers are for botany. Rather not mix the departments even more.

**Comment by izac112** [comment]
I mean they used to have two botany closets on the old maps but i can understand if you dont wanna do it

**Comment by izac112** [comment]
https://github.com/PolarisSS13/Polaris/pull/6592#discussion_r362291344 can use the xenoflorist lockers once they get merged and pushed downstream to us

**Comment by RadiantFlash7** [comment]
Sounds good to me

**Comment by RadiantFlash7** [comment]
Fixed for now until xenoflorist lockers get merged downstream!
