### ISSUE TITLE
borgo icepicks 

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#416]
Give all borg modules that lack a welder ice picks for getting past frozen airlocks since you know, they are working on a site with that being a common issue and should be ready for it

**Comment by gozulio** [comment]
I knew I forgot something.
Other borg tools should work on the airlocks. If not I'll have to fix that.

**Comment by benj8560** [comment]
have not tested it at all so could be that crowbars and stuff work dunno if so at least make sure every module has something it can use for it if other sharp or chisel like items work. I asked Izac and he was unsure if much else other then a welder and pick would work

**Comment by gozulio** [comment]
https://github.com/Yawn-Wider/YWPolarisVore/blob/abe54115fb71c3464a74996bda64012727e9ad62/maps/yw/cryogaia_things.dm#L330-L331

anything of type weapon can be used to scrape ice off a door. Unless it's something like a crayon.

**Comment by benj8560** [comment]
hmm I think even the basic borgs all have at least a crowbar or something so yeah proly ok

**Comment by gozulio** [comment]
borg tools are separate items from normal tools but they should still be of type weapon

**Comment by RadiantFlash7** [comment]
@gozulio So is this something I can close? Or are you planning on adding seperate borgo iceaxes?

**Comment by Hawk-v3** [comment]
@gozulio Yo.
