### ISSUE TITLE
Debris field has 2 destinations in shuttle console.

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#418]
#### Brief description of the issue
Upon jumping to borealis orbit, theres 2 debris field destination in the shuttle console.

#### What you expected to happen
Only one destination, because theres only one map.

#### What actually happened
2 destinations that take you to the same place.

#### Steps to reproduce
- (Step 1)View the shuttle console when at borealis orbit.
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Removing the shuttle connector, and adding/removing the route to the destination datum only removed both from the console.
Not sure how to fix this.

**Comment by RadiantFlash7** [comment]
If, litterally anyone knows about this code, I'd appreciate the help.

**Comment by SplinterGP** [comment]
fixed since we use new travel system
