### ISSUE TITLE
AI shell issues

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#423]
#### Brief description of the issue
AI shells are unable to use most of the newer hound modules and some old ones.

#### What you expected to happen
To be able to use all the listed modules: Boozehound, Pupdozer, Blade and XenoMaid.

#### What actually happened
Their unable to use the modules.

#### Steps to reproduce
 It's obvious I don't need to explain it I hope.

#### Code Revision

Server revision:  - 2020-01-01
abe54115fb71c3464a74996bda64012727e9ad62 
 
#### Anything else you may wish to add:
List of AI shell modules: 
![dreamseeker_Wd40aGE0Y6](https://user-images.githubusercontent.com/26511091/71779682-39332e00-2f86-11ea-8151-c7da2384dec0.png)
List of borg modules:
![dreamseeker_wdFWcG1Efq](https://user-images.githubusercontent.com/26511091/71779686-47814a00-2f86-11ea-86e3-f925d1d7721d.png)

**Comment by Hawk-v3** [comment]
It's banned from using some for powercreep issues. I think Engineering and Research are there for that, Mining so they don't fuck off when there's AI stuff to be done...

**Comment by Hawk-v3** [comment]
The rest could be added, but I'd want to check with Staff.
