### ISSUE TITLE
Atmospherics Pipes missing

### ISSUE THREAD

**Issue by NESgamer190** [Yawn-Wider/YWPolarisVore#424]
#### Brief description of the issue
The title explains the problem, and as for the locations, the maintenance above security and below medbay are missing some scrubber and supply pipes, leaving a big gap between medbay and security for air supply and scrubbing.  Also a missing bent pipe in the locker room and straight pipe in cryo chamber.

#### What you expected to happen
Air flowin' and pipelines to be complete.

#### What actually happened
404:  Pipe and airflow not found.

#### Steps to reproduce
- Boot up map
- Head to areas in photos
- Despair to incomplete atmos piping.

#### Code Revision
N/A
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/58912216/71783380-056efd00-2fb4-11ea-9c72-665eb05fe627.png) (Above security and below medbay for an idea.)
![image](https://user-images.githubusercontent.com/58912216/71783400-49620200-2fb4-11ea-9785-b9067fc73fb4.png) (Part two)

![image](https://user-images.githubusercontent.com/58912216/71783407-5b43a500-2fb4-11ea-8cb1-9e31c68c729a.png) (Cryo chambers missin' a supply pipe)

![image](https://user-images.githubusercontent.com/58912216/71783414-77474680-2fb4-11ea-9b4b-808ba694b991.png) (Below the ghost, a critical bent pipe for supply missing.)

**Comment by NESgamer190** [comment]
Also of note, but in atmospherics maintenance, JUST north of the stairwell, there is a lack of upward pipes, leaving the atmospheric system NOT working whatsoever!

**Comment by RadiantFlash7** [comment]
Right, Missing pipe behind the elevator is fixed.
The Z-pipe is actually meant to be outside the atmospherics maint door to the west of the main atmos room, on the same tile as the wires transfering Zs. It goes up to a junction area in engineering itself.
The pipes cut off going towards the cryo area as expansions if someone wishes to pipe in a new maint room, Cryosleep actually gets it's pipes from the main hall to the east.

**Comment by RadiantFlash7** [comment]
Fixed remaining pipes. Will be in PR #419.
