### ISSUE TITLE
Solar shed wire fault (Take two)

### ISSUE THREAD

**Issue by NESgamer190** [Yawn-Wider/YWPolarisVore#425]
#### Brief description of the issue
Knotted wire seems faulty once more, folks.  This downward orange wire just seems to not connect to the rest of the grid below it.

#### What you expected to happen
Solar shed power to head down the rest of the orange line.

#### What actually happened
The power flow of the solar shed goes to that orange knot, before it inexplicably does not get to the rest of the orange line.

#### Steps to reproduce
- Head for the engineering cycling area after setting solars
- Pry the floor tile under the airlock
- Wearing insulated gloves, multitool the wire under the airlock, and then multitool the orange wire with the knot and see the contrast.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/58912216/71783926-7fef4b00-2fbb-11ea-9ae7-fe3c20d59336.png) (Knotted wire was also faulty it seems.  Chatlog will also help on explaining where it's buggy.  Thankfully, this is a bug that can be easily remedied with cutting the knotted wire and re-setting it, but still lookin' for crew convenience.)

**Comment by RadiantFlash7** [comment]
@NESgamer190  fixed in PR #419. Due to issues with merge lastnight it did not hit the server.
Still fixed, just not merged yet.
