### ISSUE TITLE
Material Sheet special locker for science

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#429]
#### Brief overview of the feature
It's a special securised locker within science. Or a bluespace crate wrenched in place next to the autolathe, let alone in place of one of the walls, letting miners fill it from outside the desk.

The materials brought from mining can be stored there instead of laying on the floor. 

It has an ID lock to Sci access. 

Perhaps the RD can lock any withdrawal of specific sheets, namely precious Phoron, diamond, Verdanium, Mydrogen, Morphium, and so on.

This locker would have a menu to display a list akin to the stacking machine in mining out of the ore processor, and it would let your remove any number of sheets at your convenience, given you have access.

#### What you want to happen

For the RnD desk to stop being absolutely gobsmacked with materials into a cluttering mess of gold, silver, uranium, metal, phoron, plastic, diamond, plasteel and so on, like it's a massive box of legos.
 
#### Anything else you may wish to add:
I'd recommend taking example on the ORM (Ore Processing Machine) from paradise server who already does that very simply, storing materials and dispensing them given proper access clearance.

**Comment by Repede** [comment]
You could simply order secured science crates from cargo. Give them more work to do before they bore themselves up death and fill all floors with wood.

**Comment by Repede** [comment]
But a locked vendor similar to the bartender's fridge that accepts only material and is RnD locked *could* be a interesting addition.

**Comment by RadiantFlash7** [comment]
In my opinion, This is exactly what the cargo warehouse is for. Mining shouldn't be shoving Science so many minerals they have no where to put it.

**Comment by izac112** [comment]
^^
