### ISSUE TITLE
Spider corpse in Science is bluespaced into existence

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#430]
#### Brief description of the issue
There's a little spiderling corpse next to the RD office, that cannot be cleared by normal means, nor dragged, let alone picked up or squashed. It can only be disposed by a slime's cleaning feet ability, or a cleaning nade.
Otherwise it looks like a normal spiderling just Vibing forever.

#### What you expected to happen
I'd expect that spiderling corpse to actually melt and go away when I bash it with a welder 22 times, let alone the first time.

#### What actually happened
It's impossible to remove unless by very specific means, making no sense.

#### Steps to reproduce
1- Apply Hate For Spiders on that spiderling corpse
2 - It's still there unscathed, looking like a real one, at that, it's sprite that of an alive mob.
3 - Fulminate with deep hatred

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Repede** [comment]
Soap, cleanerborg feet, spray, etc will all clean it. Cleaner grenade was just overdoing it for the sake of overdoing it.

**Comment by RadiantFlash7** [comment]
This is a bug! But not the kind you report.
