### ISSUE TITLE
Photocopiers for the Paperwork Gods

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#431]
#### Brief overview of the feature
The HoP, RD and likely the other heads of staff office are furnished with a functional photocopier.
The Library too.

#### What you want to happen
To have photocopiers ready for use within Head of Staff offices, instead of only one taking the dust in SEC because they certainly needed one there apparently !
Let alone the HoP itself who /really/ ought to have one at the very least.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by benj8560** [comment]
also bridge is missing a file cabinet and photocopier

**Comment by RadiantFlash7** [comment]
I fixed this in dev, was gonna wait to make the pr before commenting but, There will be on in the conference room now.
