### ISSUE TITLE
More Shovels and Ice Pickaxes

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#432]
#### Brief overview of the feature
The Escape/Arrival zone provides adequate amounts of Snow Coats, Winter Boots, Shovels and Pickaxes for crew.

#### What you want to happen
Currently, the escape/arrival area provides adequate numbers of snow coats and boots, but less than a handful of very important tools for anyone planning to /use those coats/ and go outside.

I'd recommend there's a proper furnishing of the tools as abundant as there are coats and boots, especially within that tiny storage room near the escape arm with the 6 shelves of warm clothing.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
Going to add a cargo crate for this instead.
