### ISSUE TITLE
rood windoor

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#434]
#### Brief description of the issue
Main windoor to Anomalous Materials Lab has the incorrect access requirement.

#### What you expected to happen
The door to bloody open with my ID.

#### What actually happened
It did not big ree.

#### Steps to reproduce
- (Step 1) try and open the door.
- (Step 2) scream at the door since it does not open.
#### Code Revision
 Server revision:  - 2020-01-06
c4c2761fe5056f5f0de15bf36f1032e218bfb71c 

#### Anything else you may wish to add:
![dreamseeker_bJEWP5UyQe](https://user-images.githubusercontent.com/26511091/71867126-db622b80-30d6-11ea-901b-82e39673bd4f.png)

**Comment by RadiantFlash7** [comment]
Fixed in dev!
