### ISSUE TITLE
 Most high security place on the map having poor security aaaaylmao

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#435]
#### Brief description of the issue ####
Vault blast door button is lacking ID lock.
#### What you expected to happen
it to be ID locked so that dastardly clown (Pantsu) does not blow us all up.

#### What actually happened
It is not ID locked anyone can use the button

#### Steps to reproduce
- (step 1) push button and see half the work is done for you already.
- (Step 2) hack in and use admin powers to spawn disc and check codes
- (step 3)  blow the bitch up
- (step 4)  profit!
- (step 5) blame pantsu for everything and watch him get lynched.
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)

 Server revision:  - 2020-01-06
c4c2761fe5056f5f0de15bf36f1032e218bfb71c 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Yes I got bored making this bug report pantsu is nerd.

**Comment by Shadow-Quill** [comment]
Well, you'd need the disk, codes from Central, as well as hacking/breaking into the vault in the first place. Also the vault is in the bridge, which needs head access anyways.

**Comment by RadiantFlash7** [comment]
Still, I'll access lock the button. Small oversight.
Disk /is/ on station though.

**Comment by benj8560** [comment]
I was memeing :P I know all of these things

**Comment by RadiantFlash7** [comment]
Fixed in dev.
