### ISSUE TITLE
Daredevil trait is useless 

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#439]
#### Brief description of the issue

Daredevil Positive Trait does not seem to do anything I would guess it would allow you to run over tables like Tesh unless I am wrong. It has legit never worked since it was added ages ago

#### What you expected to happen
The trait to do something.

#### What actually happened
it seems to be useless unless I am misunderstanding it

#### Steps to reproduce
- (Step 1) Set up a custom species with the perk
- (Step 2) Try and run into a table and watch as you get stopped by it and big cri

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)

 Server revision:  - 2020-01-09
88ea30fbb35b0cdfd97e37500eb14981f5f7362d 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
I /think/ it lets you slip over railings?

**Comment by Dwaggy** [comment]
Nope. It was ment to let you do everything teshari style, jump over tables and obsticales, -including- railings and the like, much like how tesh move.
so yeah this is broken. not sure why or how to fix exactly though, John implimented this and the 'improved' bloodfeeder traits. and neither apparently work, and i don't know why.

**Comment by benj8560** [comment]
yeah well at worst maybe just remove it so it is no longer screwing up everyone with how it does nothing until it is working correctly

**Comment by benj8560** [comment]
I wanted that trait for the longest time so I would like to see it working
