### ISSUE TITLE
robotics mapping issue

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#441]
#### Brief description of the issue
Robotics is missing a set of jumper-cables necessary to reviving dead FBP/robots. 
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)

 Server revision:  - 2020-01-09
88ea30fbb35b0cdfd97e37500eb14981f5f7362d 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
Pretty sure it's not?
