### ISSUE TITLE
Syringes only have one sprite now.

### ISSUE THREAD

**Issue by Sgtwok** [Yawn-Wider/YWPolarisVore#46]
#### Brief description of the issue
I assume that when we removed the caps on syringes, we lost the other sprites for syringes

#### What you expected to happen
The syringe to change to a 'filled' icon with the color of the filling based on what it was.

#### What actually happened

The Syringe had the same exact sprite upon doing.. Well, anything.
#### Steps to reproduce
- (Step 1)
Find a syringe
- (Step 2)
Extract someone's blood or fill it with something
- (Step 3)
Be confused and lose the syringe.

#### Code Revision
 - 2018-10-17
ea2cf1efedf5b8049cbb61fa948ad42e72fb1106 
 
#### Anything else you may wish to add:
This is very.. Well, bad for doctors who might need to use several syringes at once. Something i'm sure Dwaggy can attest to.

**Comment by Hawk-v3** [comment]
We never removed these. It's Vore's issue. It's a pain, sure, but it's upstream.

**Comment by Hawk-v3** [comment]
Works now.
