### ISSUE TITLE
[Cryogaia] Pool/Gym restroom doors incorrectly named

### ISSUE THREAD

**Issue by the-og-gear** [Yawn-Wider/YWPolarisVore#462]
#### Brief description of the issue
The unit doors in the Cryogaia's pool/gym unisex restrooms are mis-labelled as 1, 1, 2, 3

#### What you expected to happen
The doors to be labelled as 1, 2, 3, 4

#### What actually happened
The doors are labelled as 1, 1, 2, 3

#### Steps to reproduce
- Go to unisex restrooms connected to the pool/gym
- Look at unit doors
- See 1, 1, 2, 3
- Cry because you realized you forgot how to count to 4 as well :(

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- Unisex Restrooms connected to pool/gym
![unknown](https://user-images.githubusercontent.com/9438930/72424144-8451fb80-3753-11ea-9f9e-49d00e0034b1.png)
![unknown_1](https://user-images.githubusercontent.com/9438930/72424145-8451fb80-3753-11ea-8100-a9aaf22be0a3.png)
![unknown_2](https://user-images.githubusercontent.com/9438930/72424146-8451fb80-3753-11ea-8bac-42418195f3ab.png)

**Comment by RadiantFlash7** [comment]
Well, You see, Theres a method to my madness. And it’s that apparently I wasn’t thinking straight. I’ll fix this in the upcoming patch.

**Comment by RadiantFlash7** [comment]
Fixed.
