### ISSUE TITLE
[Cryogaia] Wire in Cyborg Storage near the AI chamber does not produce power.

### ISSUE THREAD

**Issue by Holdelta** [Yawn-Wider/YWPolarisVore#463]
#### Brief description of the issue
Wire shown in the picture does not take power from the grid.

#### What you expected to happen
For the Cyborg Storage to be powered at round start.

#### What actually happened
The Cyborg Storage is unpowered.

#### Steps to reproduce
- Go to Cyborg Storage at round start where no one has tampered with the power.
- Use a multitool on the wire pointed out in the screenshot.
- Note that no power flows through it.

#### Code Revision
Server revision:  - 2020-01-14
2f778a08d4bac1fa9cff00a919bb7e171edea6d8 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/7005665/72432856-ee1ad700-374c-11ea-9f31-70045d4d7653.png)

**Comment by RadiantFlash7** [comment]
currently fixed in PR #453
Thank you for making an issue though. I’ll leave this up till the PR goes through.

**Comment by TheFurryFeline** [comment]
Can also put in the original post any keyword of `closes`, `fixes`, or `resolves` #issuenumber so it automatically closes the concerning issue when a PR's merged.

**Comment by RadiantFlash7** [comment]
> Can also put in the original post any keyword of `closes`, `fixes`, or `resolves` #issuenumber so it automatically closes the concerning issue when a PR's merged.

What is this github wizardy. How does one learn this kind of power?!

**Comment by TheFurryFeline** [comment]
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by RadiantFlash7** [comment]
Fixed!
