### ISSUE TITLE
Fennecs from far diced by deathclaws (Map issue)

### ISSUE THREAD

**Issue by NESgamer190** [Yawn-Wider/YWPolarisVore#466]
#### Brief description of the issue
The faction clash between fennecs and deathclaws ends up with the deathclaws promptly killing the fennecs with no chance whatsoever.

#### What you expected to happen
Fennecs to be left alone by the deathclaws

#### What actually happened
Deathclaws kill the fennecs.

#### Steps to reproduce
Just let the round start, and see the faction mishaps do things out.

#### Code Revision
A simple readjustment of the Fennec's faction to Awaymission should do the trick?
 
#### Anything else you may wish to add:
- Away Mission Borealis 1a (Image below of the unfortunate fennecs)
![image](https://user-images.githubusercontent.com/58912216/72495727-8b314a80-37f5-11ea-8d8e-ed7c327e3e27.png)

**Comment by Hawk-v3** [comment]
Fennecs don't deserve mercy. But technically this isn't a bug, by code, WAI, factions and all.

**Comment by RadiantFlash7** [comment]
I should remove these fens at some point. No reason for them to be at whiskey outpost.

**Comment by RadiantFlash7** [comment]
Derpy fennec's removed.
