### ISSUE TITLE
Vasilissan and Xenochimera Not working cold handles

### ISSUE THREAD

**Issue by SplinterGP** [Yawn-Wider/YWPolarisVore#467]
#### Brief description of the issue
Xenochimera and vasilissan are supposed to have different cold reactions(the vasilissan would enter a type of stasis) but the code don't works and all, because who made it probably dind't test

#### What you expected to happen
Both of them treat cold differently, not like a normal human

#### What actually happened
They get hurt by cold by burn damage normally, Actually the vasilissan also gets blurry vision because on the cold handle they would, but ONLY the blurry vision works

#### Steps to reproduce
- Get any of the species
- Go at cold and Just takes burn damage 
- Also look at the code and see there are things that are *wrong*

#### Code Revision
- Server revision:  - 2020-01-15
117d09b1619344813f26148791473cf671116098  (actual server revision i wrote this, i tested it some weeks ago but i doubt it changed)
 
#### Anything else you may wish to add:
- This is probably a bug report to try to see what's wrong with it and try to fix together, or even try to make it work in another way, feel free to give suggestions

**Comment by SplinterGP** [comment]
i'll post everything that i find relevant at the comments, maybe tomorrow, basically what both do is use a special handle to cold, ignoring normal one and using it, but its not working so its deactivated, The xenochimera one seems that it has a code separated from the species DM file that has a handle for the damage they take while on their cold handle, While vasilissan one should just be an alteration on the shockstate, or be it with some stuff

**Comment by SplinterGP** [comment]
``if(H.bodytemperature <= 260) //If they're really cold, they go into stasis.
		var/coldshock = 0
		if(H.bodytemperature <= 260 && H.bodytemperature >= 200) //Chilly.
			coldshock = 4 //This will begin to knock them out until they run out of oxygen and suffocate or until someone finds them.
			H.eye_blurry = 5 //Blurry vision in the cold.
		if(H.bodytemperature <= 199 && H.bodytemperature >= 100) //Extremely cold. Even in somewhere like the server room it takes a while for bodytemp to drop this low.
			coldshock = 8
			H.eye_blurry = 5
		if(H.bodytemperature <= 99) //Insanely cold.
			coldshock = 16
			H.eye_blurry = 5
		H.shock_stage = min(H.shock_stage + coldshock, 160) //cold hurts and gives them pain messages, eventually weakening and paralysing, but doesn't damage.
		return``

**Comment by TheFurryFeline** [comment]
https://github.com/Yawn-Wider/YWPolarisVore/blob/846e60440dfe47fd7d0c089c7ae32fe73ae3421a/code/modules/mob/living/carbon/human/species/station/station_special_vr.dm#L89
https://github.com/Yawn-Wider/YWPolarisVore/blob/846e60440dfe47fd7d0c089c7ae32fe73ae3421a/code/modules/mob/living/carbon/human/species/station/station_special_vr.dm#L409
are where it's meant to be handled. I don't see any forced sleep() there, though, so that's probably why if this is what's meant to happen.

**Comment by SplinterGP** [comment]
> are where it's meant to be handled. I don't see any forced sleep() there, though, so that's probably why if this is what's meant to happen.

From what i've seen https://github.com/Yawn-Wider/YWPolarisVore/blob/846e60440dfe47fd7d0c089c7ae32fe73ae3421a/code/modules/mob/living/carbon/human/life.dm#L1513

It's where it handles, to knock them

**Comment by SplinterGP** [comment]
i think at all this will need to be coded differently than with the shock_stage, will probably be easier too,

**Comment by SplinterGP** [comment]
this was solved ree
