### ISSUE TITLE
Translators don't work on several languages

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#470]
#### Brief description of the issue
Unless that's actually meant ICly, the handheld translator, the earpiece, or the circuitry-hand-made translators won't translate certain languages (such as Vox, for instance, among several others).

#### What you expected to happen
To understand what the other was saying in it's native tongue.

#### What actually happened
I did not understand what the other was saying in it's native tongue.

#### Steps to reproduce
1-Have aliens talk to you in alien languages while you're using translating gear.
2-You didn't understand what they said.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Hawk-v3** [comment]
Translators are coded to deal with specifics only and not know others. It won't do Rootspeak either. This could be changed, but by code, it's working as intended last I knew.

**Comment by Shadow-Quill** [comment]
Yep, anything with the `machine_understands` set to zero can't be translated with a tape recorder/translator/etc

**Comment by izac112** [comment]
some languages are not based on vision or sound so no matter how good, the translator would not really help.
