### ISSUE TITLE
The Autolathe should be able to print shovels and Ice pickaxes on a snow station called "Cryogaia"

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#471]
#### Brief overview of the feature
The autolathe's "tool" menu now also offers to print shovels and ice pickaxes wich are a regular need on a space station based in a world of snow. At a default to have more provided at the arrivals/escape area, and the few airlocks around the station.

#### What you want to happen
To make it less of a struggle to have cheap, but still pretty important tools, which should really be common issue and provided in numbers.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
Fixed per 591.
