### ISSUE TITLE
Phorochemistry lab fixes

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#473]
#### Brief overview of the feature
The Phorochemistry lab could really use :
-One or two more lights to see what you're doing - the locker room on the other side of the window could seriously use some too by the way
-One oxygen bottle dispensed with the space suit- unless you're meant to go fetch one in xenoarcheology in the mines
-Shouldn't the bio hazard suit also immunize you from the dangerous smokes? currently it doesn't- even with internals
-One Chemmaster to go with the chem dispenser
-One chem fridge to store any discovered/produced chemicals trough the lab

#### What you want to happen
As listed above, it's just small fixes, than actual bug or features- albeit the bio hazard suit with internals still not fully sealing you from dangerous gases does seem like a bug.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Shadow-Quill** [comment]
Need to wear some type of gloves with the bio suit, or just wear the EVA suit. Internals have no effect afaik.

**Comment by RadiantFlash7** [comment]
Biosuit is being removed,
I can add lights happily,
I genuinely didn’t think about a chem fridge. Whoops.
I also apparently forgot an oxygen tank.
A chem master however, will not be added, partly for balance reasons.

**Comment by Shadow-Quill** [comment]
Building chem masters will be possible once we get updates from upstream, too.

**Comment by RadiantFlash7** [comment]
Thank you upstream. I hate your face.

**Comment by Shadow-Quill** [comment]
Rude :'(

**Comment by RadiantFlash7** [comment]
Changes made.
