### ISSUE TITLE
Print an exploration pinn to add onto guns at the protolathe, more exploration options.

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#475]
#### Brief overview of the feature
The explorators don't have to beg for lethals anymore !
Scientists can add a little node onto any Advanced Energy gun that'll make it unable to fire within the station, just like their own frontier phasers.
That node would have the sprite of a little proximity sensor ; It could also act as a locator for SEC/the warden's monitoring of the weapons.
It can blink a little gray light like the exploratory radio channel.
It could be applied on any gun ordered at cargo as well, should SEC want to.
That node would be available to print for really cheap at the protolathe, with just some levels of electromagnetic, materials, maybe a little blue-space.
It would also modify the sprite of it's applied gun so it is now visible, apparent, like a blinking grey light over the handle of the gun.
It goes without saying that only things like an Emag should be able to remove that node.

There's also the options to print out upgraded frontier phasers who recharge faster, or have more battery, etc.

It can also instead be a selection of upgrades to add onto the phasers, limited by their capacity, exactly like mods for the mining Kinetic Accelerators.

There's also the option that the exploration vendor could, with enough points, give out a little data disk to apply at the RnD console, that would unlock those upgrades to print, once enough levels are researched.

The idea is for exploration to promote involvement, roleplay and scanning of their environment and the creatures, teamwork between the science and exploration crew, like the game is supposed to.

#### What you want to happen
For exploration to have more gear and options for the game and their expeditions, adding privileged teamwork between departments, without becoming even more of a lawless murderbone militia and improvised SEC officers, at least station side.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
A better frontier phaser sounds like a good idea.
Not so sure about the whole vending data disks thing seeing as your suppose to bring stuff back from 'alien' areas that help you bring the levels up and unless we limit scanning to only stuff on expeditions sites and not anything on station.


As regards to the pins take a look at #464

**Comment by RadiantFlash7** [comment]
I actually really like the idea of making explorer phasers upgradeable like thr KA.
Provide x amount of upgrade space, and give explorers the choice on how to setup their gun

**Comment by KillianKirilenko** [comment]
I actually have an old 99% finished PR for Cit that I never actually wrapped up for various reasons, which added four new exploration 'blaster' weapons (pistol, carbine, rifle, DMR).

Might dust that off sometime if folks are interested.
