### ISSUE TITLE
The cloner doesn't need any upgrades, science feels meaningless

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#476]
#### Brief description of the issue
I had to use the cloner. My character's body was produced to a full 100 health without genetic nor brain damage, the sleever gave me a NIF and a backup implant immediately, and I was instantly, completely able to walk, run, move and interact perfectly fine.
None of the grower pod or the sleever were upgraded.

#### What you expected to happen
Shouldn't a non-upgraded grower pod give out bodies with :
-/severe/ genetic damage?
-/severe/ brain damage?

Shouldn't an un-upgraded resleever leave you:
-heavily sick and actually disoriented, making you crawl around like if you were drunk, in a random direction other than the one you're trying to move to ;
-without a new backup implant ;
-possibly without a NiF or AT LEAST force your Nif a full 5 or 8 minutes to readjust for good measure?

My point is, right now, upgrading this /very important medical equipment/ means nothing if the bodies are grown at full health, if the sleeving is immediate and perfect, if the NIF of your character is already completely fully functional.

#### What actually happened
Death felt meaningless,
it makes upgrading the machines as a science staff feel meaningless too.
I had a new backup implant at the same moment I was sleeved back in my body,
I was ready to just go die right now and again with zero consequences,
it was a mere inconvenience of time.
I get that it's kind of the point of cloning, but. I think you get my point too.

#### Steps to reproduce
1- Die
2- realize medical doesn't need you to upgrade their equipment as everything /actually/ already just works perfectly.
3- realize science is useless for medical as they don't even need the blue beds nor fancy surgery tools nor golden health scanners in the first place anyway.
4- remember the self-repairing and healing organs you can unlock and print with hyper parts thanks to arcane levels are kinda never going to be used anyway.
5- realize science has nothing other to do for the whole shift other than upgrade medical, maybe fancy a couple VTEC to the borgs, make 3 shells for the AI that will never be used, some batteries for officers and shields that'll never have anything to shoot at anyway.
6- floor the sci desk with dozens of hundreds of expensive materials and stacks in pretty colors.
7- Shrug in mining

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
That is why we got the sleeving sickness, its 25 min and with science upgrades it can be brung down to 15

**Comment by TheFurryFeline** [comment]
Regarding the suggestion to have resleeving remove a player's NIF: _**No.**_ They're one of the few continuous items that a character can have round after round and be used for scenes and the like. Sure, if you don't have a backup before dying, definitely that's on you and should deserve NIF loss. 

Backed up _with_ an implant and died in cases where you either get digested or not? Resleeving grows your body with all synth organs inside because if ya got a heart that's assisted, ya won't like being cloned again only to die. It's a similar thinking about NIFs sticking with ya through and through.
