### ISSUE TITLE
Some of the camera tabs are empty, camera buttons glitch out on clicking

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#477]
#### Brief description of the issue
Some of the camera tabs are empty and have no cameras apparently, namely  "Exploration", "Outside", "Telecommunication", "Cryogaia".

There's also a very specific tab for interrogation rooms in SEC? For reasons?

On top of that, clicking trough the cameras will toggle not just the one camera you're pointing at, you'll apparently toggle 3 of them.

When you click /one/, the following cameras to the left and right of that button will blink as if you clicked all 3 simultaneously,
and their names will also change to the middle one you just clicked.
It's very weird. Not sure I made myself clear.

#### What you expected to happen
To have cameras in every tab,
to clic one button for one camera, without the selection of cameras visually glitching out, while my screen is jumping to display the camera I just clicked onto.

#### What actually happened
Empty cameras tabs, from "Exploration", "Cryogaia", and "Outside"

The UI glitched out all weird...

#### Steps to reproduce
1- Use the camera monitor

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Multiple cameras being highlighted after one is clicked is a mapping issue with c_tag vars. Blank categories are either because the network related camera weren't mapped in or it's something in cryogaia_defines or whatever other file handles that list of camera cateories that can be seen. Interrogation, imo, is basically something that should be merged into security as a whole.

**Comment by SplinterGP** [comment]
Maybe the ones that has no camera is because they don't exist yet, not sure about exploration but i think telecomms dont has yet, atleast last i remember
