### ISSUE TITLE
Library lacks a scanner

### ISSUE THREAD

**Issue by Championfire** [Yawn-Wider/YWPolarisVore#478]
#### Brief description of the issue
The library lacks a scanner for book uploads to the archives. This makes it impossible to upload new books to the archives. 

#### What you expected to happen
The scanner to be there so I can upload a book.

#### What actually happened
Scanner was missing, and as a result, no ability to upload a book, as the scanner was not existent in wireless range.

#### Code Revision
25fe82bcf894581c10d303f622fda82a20c763ef 
 
#### Anything else you may wish to add:
- Library

**Comment by TheFurryFeline** [comment]
Easily resolved as a map-edit.

**Comment by RadiantFlash7** [comment]
Fixed.
