### ISSUE TITLE
people using the teleporter together to exit the game will drop off their ID

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#481]
#### Brief description of the issue
a borgo would exit at the teleporter with people in their medibelly, and there'd be their ID left on the floor.
https://cdn.discordapp.com/attachments/444970133694316546/667717053800775684/unknown.png
This happened several times, including with a Command ID card..

#### What you expected to happen
For the ID to go away with their owner

#### What actually happened
The ID was left on the floor

#### Steps to reproduce
1- use the teleporter with someone else's medibelly or such
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by RadiantFlash7** [comment]
This is an issue with all vored mobs, I’ve noticed.

**Comment by TheFurryFeline** [comment]
Related to https://github.com/VOREStation/VOREStation/issues/6233
