### ISSUE TITLE
RD's access is botched

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#485]
#### Brief description of the issue
the guest pass machine will mention the RD's access to include several things on top of science, such as SEC, the morgue, AI rooms, but won't open any 

On top of This, if they should be able to bring borg'd corpses to the morgue, that's need to include basic medical access

Should roboticist attend the morgue with borg'd corpses too, that means they need basic medical access too

If a "scientist" is meant to run around the various SCI department including robotics, that'll include morgue and medical too, if you really mean to push that logic

I'd imagine they won't, and simply have to rely on actual roboticists or the RD if those do get that access of medical>morgue

#### What you expected to happen
For the RD to be able to access AI rooms, basic SEC access like any head should, and access to the morge should they be responsible of bringing borged corpses there. Same for roboticists.

#### What actually happened
No access despite the guest pass machine mentioning them being present on the RD's card.

RD can't do much of thei AI things they should be able to, other than their AI restoration console already in their office, of the consoles within the bridges

I can imagine other head's access also needs to be looked at

#### Anything else you may wish to add:
Consider also giving basic mining access to the smelting machine, maybe

**Comment by Dopiotl** [comment]
Add how RD has PF access, the PF's locker and office,
but not the explorator lockers nor the field medic lockers, or expedition weaponry cabinets

**Comment by RadiantFlash7** [comment]
@Dopiotl If I had to guess, this likely has to do with doors requiring more then one access type to open.

**Comment by benj8560** [comment]
also I think I pointed out before that RD is suppose to be able to get to tech storage but can not since it is stashed away in engineering

**Comment by Dopiotl** [comment]
add the telecoms door will open to the RD right now, just fine, but RD can't interact with the turret control pad right next to the door, wich is kinda important

**Comment by Dopiotl** [comment]
it looks as if either the RD starts to have basic access to most departments like if it was intended
OR the map gets changed with backdoors just for that instead, from maint tunnels, if you'd rather not have RD with basic med or engineer access
Not sure what alternatives

**Comment by Dopiotl** [comment]
little update, apparently to get into xenobotany you need robotics access?

Also will this access problem get solved eventually soon? It's been a month by now, even a small update would be great.

**Comment by Dopiotl** [comment]
https://cdn.discordapp.com/attachments/644996409829097512/680854667655512082/unknown.png

**Comment by RadiantFlash7** [comment]
RD's access looks about fine to me, honestly.
Medical will be responsible for morgueing corpses.

**Comment by izac112** [comment]
Is this issue relevant or should it be closed @RadiantFlash7 ?

**Comment by izac112** [comment]
Fixed according to Dopiotl
