### ISSUE TITLE
The bar should have a coffee machine

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#486]
#### Brief overview of the feature
The bar has a coffee machine because it makes sense.

#### What you want to happen
The bar has a coffee machine with it's selection of drinks and reagents to make mixes from it's recipe list
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
The bar is for drinks, the Coffee shop is for coffee, mostly to actually give people a reason to use the coffee shop, though the soft drinks dispenser in the bar can dispense coffee

**Comment by RadiantFlash7** [comment]
Pretty much the rationale Izac mentioned.
No need to make the cafe useless.
