### ISSUE TITLE
Detective's outside windows seem meant for privacy, but isn't private

### ISSUE THREAD

**Issue by Repede** [Yawn-Wider/YWPolarisVore#487]
#### Brief description of the issue
Detectives have a button to darken the windows to their office, but the airlock is made of glass so is see-through.

#### What you expected to happen
Replace airlock with non-seethrough, or replace glasses with shutters instead.

#### What actually happened
![image](https://user-images.githubusercontent.com/5666820/72673070-3549e600-3a33-11ea-8cf0-0c159bc70639.png)

**Comment by the-og-gear** [comment]
It's "privacy", obviously!

Honestly though, an idea is popping up from this that would cause even more airlock types to exist...

**Comment by SplinterGP** [comment]
Just changing for a non-glass airlock should do, it won't stop sight anyway since the windows when not tinted already lets you see

**Comment by TheFurryFeline** [comment]
Aye, non-glass airlock will make sight-lines blocked.

**Comment by RadiantFlash7** [comment]
...Whoops. This was meant to be nonglass.

**Comment by RadiantFlash7** [comment]
Fixed.
