### ISSUE TITLE
robotics has no bodybags, unreachable sleep red locker, some fixes

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#489]
#### Brief overview of the feature
Robotics has one box of body bags since they borg people, producing corpses. One spray bottle of space cleaner too. A box of surgery gloves. A box of surgery masks.
The unisex restroom east of the RD office could have one soap.

It kinda also follow my other post about robotics/the RD having access trough to the morgue- unless they are meant to rely on medical crew for disposing of bodies.

Also apparently the only way to use the sleep locker at the operating table is by climbing over the table, over the tools.

It'd also be really good for robotics to have an actual full set of surgery tools, or at least the surgical drill when they want to put a NIF inside a synth- unless they are meant to print one surgical drill at the lathe.

It would also be great for robotics/science to have a second heavy-duty cell charger, as a mere quality of life.
Not sure why circuitry has one, instead of a normal charger, alongside a stack of glass sheets, when they don't use neither large cells nor glass for their circuits.

#### What you want to happen
For robotics to be autonomous on handling the corpses and to do tasks they'll have to deal with over time.
Some of the listed fixes and features.
 

#### Anything else you may wish to add:
Consider removing that table and the two windoors between Sci and robotics, maybe. Everyone just decons it.
Consider making the science desk windows to be electrochromic with a switch, alongside it's windoor? With a little desk bell?

**Comment by RadiantFlash7** [comment]
Robotics is meant to deliver bodies to medical to store. It wasn’t very feasible to get robotics access there somehow.
That said, 
Table between science and robotics is definitely staying. They’re two seperate jobs, damn it! I’ll look into fixing the other stuff

**Comment by izac112** [comment]
Fixed according to Dopiotl
