### ISSUE TITLE
Janitor windoors fudged

### ISSUE THREAD

**Issue by Shadow-Quill** [Yawn-Wider/YWPolarisVore#490]
#### Brief description of the issue

Title

![image](https://user-images.githubusercontent.com/44811257/72687653-9ae6b280-3ac5-11ea-864e-1a418a5e4ae1.png)

**Comment by TheFurryFeline** [comment]
Wew. That's one heck of an oddity. Windoors are oriented the wrong way but I still see the creases in the table?

**Comment by Shadow-Quill** [comment]
floor tile on the left, shutters on the right

**Comment by RadiantFlash7** [comment]
fixed
