### ISSUE TITLE
shield generators from the science testing range are locked to engineering

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#491]
#### Brief description of the issue
The weapons testing range in science has shield generators behind the targets, as not to break the walls behind with firearms and create a breach.
The thing is, they are ID locked to engineering. And cannot be used by science staff.

#### What you expected to happen
To be able to activate the generators as not to potentially create a breach in the shooting range.

#### What actually happened
Science crew cannot use that equipment provided for their department.

**Comment by TheFurryFeline** [comment]
https://github.com/Yawn-Wider/YWPolarisVore/blob/f914803532654806fc0004d85a937c6c5c86bcc3/code/modules/shieldgen/sheldwallgen.dm#L9 is where it's hard coded to be access_engine_equip. You can problem either add onto this or make a var-edit in the map editor.

**Comment by RadiantFlash7** [comment]
Fixed.
