### ISSUE TITLE
A piece of equipment that should not be in the chapel

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#492]
#### Brief description of the issue
A cabinet in the chapel back area has a stealth_field.

#### What you expected to happen
Not have a piece of space ninja gear in the chapel

#### What actually happened
The reverse

#### Steps to reproduce
play the game
#### Code Revision
2020-01-19
4aaba95270ca967358eec2f3e6653322845f38d2  
#### Anything else you may wish to add:
Get this fixed asap

**Comment by RadiantFlash7** [comment]
Fixed.
