### ISSUE TITLE
Phase weapons

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#495]
#### Brief overview of the feature
readd phase weapons.

#### What you want to happen
Ages ago all types of phase weapons where printable via R&D however someone had the silly idea to remove them. I think they would be hella good to readd if firing pins get ported to provided a  harmless alternative for when we have no sec but do have R&D as in for dealing with grubs and spiders. RN only a few pistols spawn at round start but all the fancy upgraded types would be nice.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Phase weapons are a weapon that can only deal large amounts of damage to most mobs if you are unaware.

**Comment by izac112** [comment]
You can order them now. Stale
