### ISSUE TITLE
Guns dont fire!

### ISSUE THREAD

**Issue by cebutris** [Yawn-Wider/YWPolarisVore#497]
#### Brief description of the issue

Probably related to firing pins. Guns, at least, regular security ones in the armory, firing range, and officer equipment, including tasers, don't fire at all
#### What you expected to happen
Pew pew

#### What actually happened
No pew. No click, either. Clicking something to fire the weapon provides no feedback, unless you're in help intent
#### Steps to reproduce
- Get gun
- Harm intent
- Click
- No pew!

#### Code Revision
![image](https://user-images.githubusercontent.com/26630607/72805890-e8783200-3c21-11ea-845c-6070ed82fa39.png)

 
#### Anything else you may wish to add:
- Was the code even tested before merging??

**Comment by TheFurryFeline** [comment]
Do you have firing intent set on dangerous in global settings? IIRC, that's where you can make yourself be able to shoot when even on help intent.

**Comment by izac112** [comment]
Fixed in #499

**Comment by TheFurryFeline** [comment]
Oh, that answers that.
