### ISSUE TITLE
botched mechas access

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#508]
#### Brief description of the issue
a medic or off-duty scientist or any civilian can swipe their ID at a mech to initiate it's maintenance protocole
It you wanted to park the mech in robotics with some slight precaution for it not to be stolen by nerds hacking into robotics, you're forced to DNA lock them, maint protocols won't do the trick anymore to just keep the mech in place

#### What you expected to happen
for that kind of access to be restricted to robotic and/or science access

#### What actually happened
any ID can apply to a mech's supposedly limited access

#### Steps to reproduce
play the game

**Comment by RadiantFlash7** [comment]
Can you not currently disable maintenance protocols?

**Comment by izac112** [comment]
You can lock the panel after setting the access for the mech if i recall right

**Comment by Dopiotl** [comment]
well, this is me initiating the maint protocols, then trying to forbid them. I get, as expected, a message that, they're in effect and I can't forbid them or such

https://cdn.discordapp.com/attachments/666815478903341064/670623020544425984/unknown.png

Unless I didn't get what you meant

**Comment by izac112** [comment]
Miss understanding in regards to key codes functions

**Comment by RadiantFlash7** [comment]
@Dopiotl all you need to do, is add a keycode, and then hit initiate maintenance once again in the tab that allows the option of editing keycodes. That will turn off maint protocols, and then you can forbid then in the main pannel.

**Comment by Dopiotl** [comment]
Yep! I didn't know the "add access" button would in fact restrict access to that
Sorry for the confusion and thank you for your time
