### ISSUE TITLE
Prototype Voidsuit Invisibility

### ISSUE THREAD

**Issue by Dio-Sama** [Yawn-Wider/YWPolarisVore#51]
#### Brief description of the issue
Prototype Voidsuit becoming broken, when placed into the suit cycler to change it's skin to a different one

#### What you expected to happen
Prototype Voidsuit simply changes skin,

#### What actually happened
Prototype Voidsuit becomes invisible due to presumably not having a different skin than the base one, It is unclickable, But shows up when you select the tile it is on with right click.

#### Steps to reproduce
- (Step 1) Get prototype Voidsuit out of HoS locker
- (Step 2) Place into Cycler
- (Step 3) Apply Customization Routine
- (Step 4) Retrieve voidsuit and realize it is invisible.

#### Code Revision
2018-10-17 ea2cf1efedf5b8049cbb61fa948ad42e72fb1106
 
#### Anything else you may wish to add:
![after-the-cycler](https://user-images.githubusercontent.com/44406956/47370690-9676f280-d6e6-11e8-8280-625500af160e.PNG)
![before-the-cycler](https://user-images.githubusercontent.com/44406956/47370693-970f8900-d6e6-11e8-8f6b-0afa812c24a2.PNG)

**Comment by Hawk-v3** [comment]
It'll have changed icon states and something will have arsed it up. I'll have this checked due to age, but, will see.

**Comment by Hawk-v3** [comment]
This suit has no species restrictions on it, but cannot be refitted as it breaks the sprites. There are no other styles of species sprite for this. It's a fluffsuit repurposed into a main item. Upstream buggered it and I'm not a spriter.
