### ISSUE TITLE
Combat boots and gloves at a set spawn locations.

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#511]
#### Brief description of the issue
Don't have a preset non random spawn location for combat boots in maint, which makes you immune to any form of slip and gives you strong defense in general to the feet.

Don't have a preset non random spawn location for combat gloves which gives you shock, heat protection and good defense in general to your hands.

#### Images
I send you a picture of the location of said items, when requested.

#### Code Revision
a88df3cc09cc6f96612f468a383dc1cbb2e9d530

**Comment by SplinterGP** [comment]
i knew about the combat boots, not about the gloves tho

**Comment by RadiantFlash7** [comment]
I request zeh location.  Toss it in the staff dev chat and ping me.

**Comment by RadiantFlash7** [comment]
Fixed.
