### ISSUE TITLE
Command soda dispenser is empty

### ISSUE THREAD

**Issue by Crystal9156** [Yawn-Wider/YWPolarisVore#516]
#### Brief description of the issue
Soda dispenser in the command conference room has no cartridges in it.

#### What you expected to happen
Walk into command conference, place cup, get drink.

#### What actually happened
Walk into command conference, place cup, get absolutely nothing.

#### Steps to reproduce
1. Walk into Conference room.
2. Look at Soda dispenser.
3. See no cartridges installed.
4. Cry in Command.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
Server revision:  - 2020-01-26
743965bba356318548a3907f86938cb267135bcc 
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Mapping issue, base soft drink without the subtype of full for the non-empty dispenser.

**Comment by RadiantFlash7** [comment]
Fixed.
