### ISSUE TITLE
Research Director's Desk requests console is innacessible/unusable

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#520]
#### Brief description of the issue
The Research Director's Desk requests console cannot be used as it is right now, behind the small secure windoor.

On top of it, when an admin moved it trying to help, it became unresponsive, no clue if that's linked with the first issue in any way tho.

https://cdn.discordapp.com/attachments/666815478903341064/671392830341775370/unknown.png

#### What you expected to happen
To use the equipment furnished for my character's job 

#### What actually happened
I could not use the equipment furnished for my character's job

#### Steps to reproduce
- Play RD
- Try to use the the Research Director's Desk requests console 
- You can't

**Comment by RadiantFlash7** [comment]
Ach! Will look into this.

**Comment by Dopiotl** [comment]
I'd like to add I'm unable to change the alert level from the computer, too

**Comment by izac112** [comment]
Fixed acording to Dopiotl
