### ISSUE TITLE
No sulphuric acid dispenser in R&D

### ISSUE THREAD

**Issue by KotetsuRedwood** [Yawn-Wider/YWPolarisVore#524]
#### Brief description of the bug
There's no sulphuric acid dispenser in the R&D research room

#### What you expected to happen
I expected to find a dispenser in there

#### What actually happened
When I ran out, I had to go over to robotics to get more acid

#### Steps to reproduce
1. Join as scientist
2. Fill circuit printer with acid
3. Run out of acid
4. Look for more
5. where is it

#### Code Revision
2020-01-27 - 1892d7be7e822a2a0102eaae688efec4df543f06 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/10330701/73328964-96ec2a80-4253-11ea-8351-814e71ebc6e0.png)

**Comment by Shadow-Quill** [comment]
Could ask chemistry or use phoronics' chem dispenser

**Comment by TheFurryFeline** [comment]
Dispenser is commonly mapped in due to the fact that the circuit printer requires it.

**Comment by SplinterGP** [comment]
Also, normally there are other parts of science that has it too, and you can always make a new one too

**Comment by TheFurryFeline** [comment]
Wait, you can make those dispensers???

**Comment by SplinterGP** [comment]
I think so? And even if there inst there is one probably in robotics

**Comment by izac112** [comment]
You cant make the wall ones, it used to have a wall dispenser before the map switch and should probably have one now

**Comment by TheFurryFeline** [comment]
Yeah, it is. Though it should also get mapped in regardless. Doing the map work now. Simple enough.

**Comment by SplinterGP** [comment]
I always was used to have to make sulphuric acid manually, dindt know about how it waa on virgo

**Comment by TheFurryFeline** [comment]
This needs to be closed since the map change was done.
