### ISSUE TITLE
screen inside window at the pool

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#529]
#### Brief description of the issue
it's a screen inside a window. mere mapping issue, really

https://cdn.discordapp.com/attachments/670983313984585758/673029453970145290/unknown.png

#### What you expected to happen
to not have a screen inside a window

#### What actually happened
screen in window because reasons

#### Steps to reproduce
1-play the game
2- walk to the arcade-pool

**Comment by RadiantFlash7** [comment]
Fixed.
