### ISSUE TITLE
There is two time clocks instead of one.(next to kitchen)

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#536]
#### Brief description of the issue
There is two time clocks instead of one.

#### Anything else you may wish to add:
next to the kitchen, https://i.gyazo.com/70adf6f1050bdd3d740665ba61c42dc8.png for image

**Comment by RadiantFlash7** [comment]
Ironically, this was a mapping mistake. However, looking at it in practice, it’s actually become a feature. People tend to clock out in pairs for *totally not suspicious reasons* and it works out in my opinion.

**Comment by SplinterGP** [comment]
make it a feature already, don't hurts IMO
