### ISSUE TITLE
Psychiatrist maintenance door not locked right

### ISSUE THREAD

**Issue by EldrinKanthos** [Yawn-Wider/YWPolarisVore#539]
#### Steps to reproduce
- (Step 1) Not be psych
- (Step 2) try maint door

#### Code Revision
- uhhh. I'm currently at work and cannot say
 
#### Anything else you may wish to add:
- Just a simple change to the door access levels.

**Comment by TheFurryFeline** [comment]
Public maint door for Psych office's back door? Definitely a mapping issue.
