### ISSUE TITLE
Mr. Wiggles spawns next to flaps that house a deadly disposal.

### ISSUE THREAD

**Issue by EldrinKanthos** [Yawn-Wider/YWPolarisVore#540]
Mr. Wiggles the therapy do spawns in psych isolation unit...next to a disposal that leads out into medbay. The flaps mean he has a random chance to wander under and into the open recepticle there to be flushed 20 feet and die.

I've wondered why he is always dead any round that isn't just starting. Seems that may be the culprit.

Solution: move his spawn to psych office? Would be simpler than moving the disposal.

**Comment by TheFurryFeline** [comment]
Mapping issue, easily resolvable by moving the spawnpoint for the pet mob. Wait.... Why is there a chute that anyone can walk into? Why not have the usual bins? 😕

**Comment by EldrinKanthos** [comment]
Dunno. But it is the chute and not bin. Looks designed to toss food in the outside bin or other items so as to give to patient without going inside.
