### ISSUE TITLE
Psych office has a chem closet they cannot use, that also has no psych meds in it.

### ISSUE THREAD

**Issue by EldrinKanthos** [Yawn-Wider/YWPolarisVore#541]
#### What you expected to happen: preferably remove the locker or change the access on it. Do not recall what is in the locker so cannot suggest any changes there.

**Comment by TheFurryFeline** [comment]
Ya know, a lot of these Psych room issues could've been consolidated into one issue post with a list. Lot of mapping issues for just one area.

**Comment by EldrinKanthos** [comment]
I know. I am sorry for that
