### ISSUE TITLE
Medical lobby desk windoors, all but one inaccessible to Pysch.

### ISSUE THREAD

**Issue by EldrinKanthos** [Yawn-Wider/YWPolarisVore#542]
#### What you expected to happen:they should be updated so that the psych can man the front desk and check the consoles there.

**Comment by TheFurryFeline** [comment]
https://github.com/Yawn-Wider/YWPolarisVore/issues/541#issuecomment-583025063 Pointing to this for the record.

**Comment by EldrinKanthos** [comment]
I'd never done these before. Apologies. As one was the office and one the medbay Desk I just logged in my head as seperate

**Comment by TheFurryFeline** [comment]
No worries, just a snippet of advice for next time if there's a whole slew of issues for an area/room/etc.
