### ISSUE TITLE
Cake hat (maybe?)

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#544]
#### Brief overview of the feature
Adding back the cake hat to the kitchen/bar again so i can be used to make birthday cakes again, thats it unless you can get it from cargo.

**Comment by TheFurryFeline** [comment]
Sounds like you're asking for it to be mapped back in.

**Comment by izac112** [comment]
yep

**Comment by Repede** [comment]
Would like to have it back yeah
