### ISSUE TITLE
Condimaster Unavailable 

### ISSUE THREAD

**Issue by EvilEnchantress** [Yawn-Wider/YWPolarisVore#547]
#### Brief description of the issue
There is no condimaster available for kitchen staff, there are however 3 different chem masters, one in kitchen, backroom of bar, and down in gardening.

**Comment by RadiantFlash7** [comment]
I’ll add it on in after work today. Probably just mixed up the chem master and condimaster by mistake

**Comment by RadiantFlash7** [comment]
replaced one in kitchen for this update.
