### ISSUE TITLE
Harsh nerf coming down from upstream regarding use of bluespace harpoons when riding taurs.

### ISSUE THREAD

**Issue by Ketrai** [Yawn-Wider/YWPolarisVore#555]
https://github.com/VOREStation/VOREStation/pull/6542
For details.

The main dangerous effect here is that harpoons get an increased chance of 20% to fail when someone uses it whilst riding a taur, or being ridden. Not only is this needlessly harsh, making it so you have a 36% chance to fail after just two teleports, you can fuck over your taur buddy willingly or unknowingly, vice versa for taur screwing over the rider. I'd rather not see this being able to be used as an impromptu murder weapon. (harpoons can teleport people into dangerous areas frequently on failure.

Probably want to look at making taur riding only affect the cooldown of the harpoon instead, or just disregard the change altogether when updating.

**Comment by SplinterGP** [comment]
To be fair only dangerous area you can teleport yourself that i know its outside, that is fine since having a snowsuit is fine, also the engine room but its just areas nearby you, there's also elevator too

**Comment by Ketrai** [comment]
Still. Do we really want this kind of nerf to confuse people? Afaik there's been little to no issue seen behind taurs using harpoons when riding folk. Often people just pick up others anyways to do so, so it's not like the nerf can't be omitted. This is just bound to inconvenience people who don't know every little detail of the code.

**Comment by Repede** [comment]
I wonder what happened that made upstream decide to add that. Though to be fair on here people rarely ride taurs, or use the harpoon in general. Plus the worse is ending up in the snow (or lasered to death in AI core/Telecomms). I imagine once the upstream update PR happens we'll have that discussion there

**Comment by SplinterGP** [comment]
i'd rather have we would just not add it for sake of making things in code less complicated really, it seems very unnecessary to me

**Comment by SplinterGP** [comment]
they probably dind't even test it
