### ISSUE TITLE
Small Maintenance Issue

### ISSUE THREAD

**Issue by StellarTheAwoo** [Yawn-Wider/YWPolarisVore#562]
#### Brief description of the issue
This partiuclar two square maintenance area lacks any radiation sheltering. The location of the place is the medical patient maintenance (a very small maintenance are).

#### What you expected to happen
Potentially allow it to be radiation shielded like every other maintenance region, though I can see why it was looked over.

#### What actually happened
Someone had used it and got major radiation levels from being inside. Easily treated, but still a headache in itself.

#### Anything else you may wish to add:
![Maintenance issue](https://user-images.githubusercontent.com/52103820/74111186-c870ca00-4b60-11ea-9c0c-22616e1fbe78.PNG)

**Comment by TheFurryFeline** [comment]
Mapping oversight, basically. I assume it wasn't mapped in with an area of maintenance.

**Comment by RadiantFlash7** [comment]
Ach. Correct.

**Comment by Repede** [comment]
Fixed in master, just do not stand on the airlock
