### ISSUE TITLE
Powernet Sensor w/ Unset ID in Monastery

### ISSUE THREAD

**Issue by KillianKirilenko** [Yawn-Wider/YWPolarisVore#573]
#### Brief description of the issue
Was running some local tests for a project port I'm working on and caught

`## WARNING: Powernet sensor with unset ID Tag! 188X 215Y 5Z`

in the server window. Corresponds with the Monastery pump shed.

#### What you expected to happen
The powernet sensor to have an ID tag.

#### What actually happened
It doesn't! Shocking.

#### Steps to reproduce
- Run server.
- Find powernet.
- Discover that it has no ID tag.

#### Code Revision
N/A
 
#### Anything else you may wish to add:
Nada.

**Comment by TheFurryFeline** [comment]
Mapping bug, to be accurate.

**Comment by RadiantFlash7** [comment]
Fixed long ago.
