### ISSUE TITLE
There is no HoP request console

### ISSUE THREAD

**Issue by cebutris** [Yawn-Wider/YWPolarisVore#578]
#### Brief description of the issue
At first I believed there was no request console in the HoP's office at all, however, there is one- hidden underneath the table with the fax machine. However, it is a Bridge request console, rather than HoP

![image](https://user-images.githubusercontent.com/26630607/74598017-7e438900-5037-11ea-9cbb-6ff1e4bd3dab.png)

#### What you expected to happen
HoP to have a request console to be able to send announcements

#### What actually happened
the request console in the HoP's office is labled as the bridge, and is hidden

**Comment by TheFurryFeline** [comment]
Offset is wrong as well as object type. Mapping issue. Not hard to fix.
