### ISSUE TITLE
Vent sounds cutting out

### ISSUE THREAD

**Issue by KillianKirilenko** [Yawn-Wider/YWPolarisVore#590]
#### Brief description of the issue
After the recent PR to 'fix' the sound duration(?), the sounds are actually cutting in and out, where before they looped just fine.

#### What you expected to happen
Vent sounds to loop properly

#### What actually happened
Vent sounds keep cutting out.

#### Steps to reproduce
- Sit near a vent
- Listen to it cut in and out

#### Code Revision
- 2950b03e5abaa1f2175c587905a21b73a7374734

**Comment by izac112** [comment]
Should be fixed next restart https://github.com/Yawn-Wider/YWPolarisVore/pull/588
