### ISSUE TITLE
Wind

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#595]
#### Brief description of the issue
Wind directions does not seem to work properly.

#### What you expected to happen
Wind to occasional switch direction and strength

**Comment by SplinterGP** [comment]
They just dont? I remember having wind

**Comment by izac112** [comment]
Last time i checked a couple of weeks ago the wind did not seem to shift / change direction and power, does it work now?

**Comment by SplinterGP** [comment]
Well i know there is wind, but probably on storms or rain, dindt see it normally out of these rains or storms or blizzards

**Comment by izac112** [comment]
Ah well good enough then
