### ISSUE TITLE
Loyalty implants

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#600]
We need to add back a lockbox of loyalty implants to the armory, because there is currently no way to get any.
Path is /obj/item/weapon/storage/lockbox/loyalty

**Comment by SplinterGP** [comment]
Should probably add it to cargo instead ? would sound better to me

**Comment by izac112** [comment]
I mean that should also be a thing but there always used to be a box of them in the armory before vore removed them from cargo and the armory

**Comment by SplinterGP** [comment]
ah yeah makes sense, also what about the stuff on loyalty implants ?

**Comment by izac112** [comment]
They are pretty vague by default because they are suppose to make the user unable to act against the interests of the company and follow their rules / orders

**Comment by SplinterGP** [comment]
wow, that's some pretty hard stuff, yeah, if were to, used only on like, Mutiny and rev stuff

**Comment by RadiantFlash7** [comment]
@izac112 weren’t loyalty implants stripped from the code?

**Comment by KillianKirilenko** [comment]
Why are loyalty implants needed, exactly? They're basically just a mechanical way of protecting the CD and IAAs from Rev/Cult subversion... and *we don't have revs or cults*.

Unless you desperately need them as a prop, surely it can just be a roleplayed scene thing?

Finally, according to the implant's own data (emphasis mine);
> Personnel injected with this device _tend to be_ much more loyal to the company.

They're not a foolproof solution and if they were they'd be a flagrant violation of slavery laws.

**Comment by SplinterGP** [comment]
NT pretty much uses it on people whn they are(explained) acting against NT, such as mutiny, Siding with invading mercs/aliens, that sorta things

**Comment by izac112** [comment]
> @izac112 weren’t loyalty implants stripped from the code?

Nope vore just removed them from the armory, cargo and cd / hos,
the path to the box is what i posted, you got any patches in the works? otherwise i can just add it myself. @RadiantFlash7 

> Why are loyalty implants needed, exactly? They're basically just a mechanical way of protecting the CD and IAAs from Rev/Cult subversion... and _we don't have revs or cults_.

Splinter pretty much explains why they are needed and how they are used and just because don't have rev rounds does not mean NanoTrasen would just stop supplying them same reason we still got an armory with ablative vests even though we don't have nuke ops. 

> Unless you desperately need them as a prop, surely it can just be a role played scene thing?

Its an item for a reason because you need to implant it, plus you can remove it with surgery (with the exception for the blue shield) its mechanical and a role play, so yes its needed and getting added back

> Finally, according to the implant's own data (emphasis mine);
> 
> > Personnel injected with this device _tend to be_ much more loyal to the company.
> 
> They're not a foolproof solution and if they were they'd be a flagrant violation of slavery laws.

Here we always used them as a fool proof solution rp wise when it came down to it, there is a reason they barely got used at all except on murderes and alike when they where still here, blue shields start with them oocly though the description can easily be updated, this should have been mapped back in when we remade the armory.

**Comment by Legion2552** [comment]
The Captain and HoS was originally Loyalty Implanted from the start. An upstream removed them for some reason unknown to me. The BSG was brought back by us with the express purpose of being Loyalty Implanted.
