### ISSUE TITLE
More Map Rad shielding inconsistency.

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#603]
#### Brief description of the issue
Bar is currently rad shielded, and not meant to be. 
Security outpost is not rad shielded and is meant to be.
Xenobio Maintenance is not rad shielded and is meant to be.

#### What you expected to happen
Radiation shielding.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by EldrinKanthos** [comment]
RIP PunPun

**Comment by TheFurryFeline** [comment]
Bar's shielded because it's a child of the crew_quarters area subtype

**Comment by RadiantFlash7** [comment]
I simply moved the rad proof var for it further down in the code for the subtype just before dorms on my branch. 
Should fix the issue.

**Comment by TheFurryFeline** [comment]
Just be sure to not make dorms deadly as a result.

**Comment by Repede** [comment]
Fixed in master
