### ISSUE TITLE
The medical laptop in Detective office does not search for records

### ISSUE THREAD

**Issue by SplinterGP** [Yawn-Wider/YWPolarisVore#613]
#### Brief description of the issue
In the laptop there is a option you can choose and search for the DNA/Fingerprint or anything else from records, however you input the DNA or fingerprint and it don't works

#### What you expected to happen
Show the records that had that fingerprint or DNA

#### What actually happened
Dind't show

#### Steps to reproduce
- (Step 1)Get a fingerprint or DNA Hash
- (Step 2)Search records on laptop computer in detective office
- (and so on)it don't works

#### Code Revision
Server revision:  - 2020-02-22
96a578d3cb86cb1988942c46d0dffada5bba81cd 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Wait.... Why is there a medical laptop? Security records already have the fingerprints in them so there'd be no need to have the laptop that's specifically for medical to use and would be a violation of privacy laws to use and pry into their records.

**Comment by izac112** [comment]
Does the sec one also have dna?

**Comment by TheFurryFeline** [comment]
Upon further testing, the sec records console does _not_ have DNA info..... However, may not be too hard to integrate that part into sec records info stuff and keep to SOP regarding medical laptop being for medical and protecting a person's privacy pertaining to their medical records.

**Comment by RadiantFlash7** [comment]
Eh. I don’t see an issue with it personally?
Then again, I found the medical SOP irritating personally, So, Yeah.

**Comment by izac112** [comment]
Should be fixed in #9522 on vorestation once we have another upstream update.
