### ISSUE TITLE
The Traveler's Guide to Human Space: Borealis Edition still refers to Virgo Erigone

### ISSUE THREAD

**Issue by Tename** [Yawn-Wider/YWPolarisVore#629]
#### Brief description of the issue
While the title of the book has been changed many areas in the book still refer to Virgo Erigone including, the home page, about section, and everything in important locations.

Also, the political section is blank and should just be deleted.
#### What you expected to happen
The book to refer to Borealis

#### What actually happened
The book refers to virgo

#### Steps to reproduce
- Get the book
- Open the book

#### Code Revision
Server revision:  - 2020-03-02
420b825864fd6ff50ada40a412b2f59d8323e4aa

**Comment by KillianKirilenko** [comment]
At this point it might be best to make a whole new codex object entirely rather than editing the Virgo one, but it's going to mean digging through a whole bunch of different files either way.

Depends on how the codex works exactly.

**Comment by KillianKirilenko** [comment]
Found how this all works, doesn't look too hard to fix up. Currently working on an update for the traffic system, so I'm going to roll a codex update into it as well.
