### ISSUE TITLE
Alraune information seems to be lacking (link from old rep)

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#63]
https://github.com/Repede/YawnWiderStation/issues/193

### MASMC commented

Brief description of the issue
There's a lack of information on the Alraune species selection page.

What you expected to happen
I expected to have all the requested information, such as an image, or the base language

What actually happened
Nice lack of such information

Steps to reproduce
Open character selection
Load a slot (any works)
Change your species
Select Alraune
Marvel at your lack of requested info!
Code Revision
Server revision: - 2018-12-09
e193dae
Anything else you may wish to add:
Here's an image!
![image](https://user-images.githubusercontent.com/12752822/50576517-8cbee900-0e13-11e9-91b2-330cbb467290.png)

### MASMC commented

Also protean have this issue, except they have the language filled

**Comment by Hawk-v3** [comment]
This is a non-YW race, so regardless of anything missing from it, it's not our issue.
