### ISSUE TITLE
VChat, Major lag when scrolling up.

### ISSUE THREAD

**Issue by Tename** [Yawn-Wider/YWPolarisVore#632]
#### Brief description of the issue
FPS drops greatly to the point of being unplayable after playing for an hour or so then trying to scroll up in your chat window.

#### What you expected to happen
My FPS not to die when scrolling up

#### What actually happened
My FPS died

#### Steps to reproduce
- Play for an hour or so, have things said, get a decently long chat history
- Scroll up
- HNNNNNNNNNNNNNNNNNGGGGGGGGG

#### Code Revision
Server revision: - 2020-03-04 

9879616e6943660c4932e159039f7becc6822cfc

**Comment by SplinterGP** [comment]
that was caused probably due a issue in time dilation, it seems to be completely fine now

**Comment by Repede** [comment]
VChat issues make a issue on vorestation directly. https://github.com/VOREStation/VOREStation/issues

**Comment by Tename** [comment]
> 
> 
> that was caused probably due a issue in time dilation, it seems to be completely fine now

No, it only happens when scrolling up.

**Comment by izac112** [comment]
> > that was caused probably due a issue in time dilation, it seems to be completely fine now
> 
> No, it only happens when scrolling up.

Just curious did you press the pause button while scrolling up and or did you increased the stored messages to more then the standard

**Comment by Tename** [comment]
> 
> 
> > > that was caused probably due a issue in time dilation, it seems to be completely fine now
> > 
> > 
> > No, it only happens when scrolling up.
> 
> Just curious did you press the pause button while scrolling up and or did you increased the stored messages to more then the standard

Just tested it again while hitting pause, still getting horrible lag.

**Comment by izac112** [comment]
aww rip

**Comment by SplinterGP** [comment]
> > > > that was caused probably due a issue in time dilation, it seems to be completely fine now
> > > 
> > > 
> > > No, it only happens when scrolling up.
> > 
> > 
> > Just curious did you press the pause button while scrolling up and or did you increased the stored messages to more then the standard
> 
> Just tested it again while hitting pause, still getting horrible lag.

try uh, reloading vchat or reconecting, or turning off animate messages, for some reason that ain't happening with me.

**Comment by Tename** [comment]
> 
> 
> > > > > that was caused probably due a issue in time dilation, it seems to be completely fine now
> > > > 
> > > > 
> > > > No, it only happens when scrolling up.
> > > 
> > > 
> > > Just curious did you press the pause button while scrolling up and or did you increased the stored messages to more then the standard
> > 
> > 
> > Just tested it again while hitting pause, still getting horrible lag.
> 
> try uh, reloading vchat or reconecting, or turning off animate messages, for some reason that ain't happening with me.

I got animations off, and reconnecting would probably fix it. I only get it when theres a lot of stuff in my logs.

**Comment by SplinterGP** [comment]
well, what's your message amount ?

**Comment by SplinterGP** [comment]
on the configurations ? the default is 100, you gotta click out of the typing box to save it

**Comment by Tename** [comment]
> 
> 
> on the configurations ? the default is 200, you gotta click out of the typing box to save it

You sure its 200? I got 2000 when I first connected

**Comment by SplinterGP** [comment]
yeah, set it to 200, that's probably what causes the lag, the default is 200, you can see it by hovering the mouse over the option

**Comment by SplinterGP** [comment]
it may have been from another connection you made on the other testmerge where that was the limit it would go, so it saved that amount

**Comment by Tename** [comment]
I set it to 200, it seems a lot less chuggy but its still stuttery for sure.

**Comment by SplinterGP** [comment]
hmm, odd, try waiting some time and see, for me its pretty fine scrolling, oddly

**Comment by Tename** [comment]
Like its usable for sure at 200, but I still get a little stutter, it might be because I am on Windows 7, maybe.

**Comment by Repede** [comment]
it's definitely choppy if I use the scroll wheel to try scrolling chat, but dragging the scrollbar seems much smoother (at 200 messages)
