### ISSUE TITLE
VChat logging system doesn't continuously save 

### ISSUE THREAD

**Issue by Tename** [Yawn-Wider/YWPolarisVore#633]
#### Brief description of the issue
When exporting chat logs, unlike the old system Vchat only saves your current chat history and doesnt continue to fill with new messages,

#### What you expected to happen
My chat logs to keep saving after I exported history

#### What actually happened
It didnt

#### Steps to reproduce
- Say something
- Export history
- Say something
- View file

#### Code Revision
Server revision: - 2020-03-04 

9879616e6943660c4932e159039f7becc6822cfc

**Comment by SplinterGP** [comment]
that's known and it's a limitation, however when saving at round end or before going out it will export even the ones who don't show in your chat, all way back

**Comment by SplinterGP** [comment]
also take all vchat issue to vorestation github

**Comment by izac112** [comment]
^^

**Comment by Tename** [comment]
Alright
