### ISSUE TITLE
VChat, make default file name include the date and time

### ISSUE THREAD

**Issue by Tename** [Yawn-Wider/YWPolarisVore#634]
#### Brief overview of the feature
When exporting log history make the file name include the date and time instead of just being Chat_export

#### What you want to happen
All that I want is in the overview
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
Put it here https://github.com/VOREStation/VOREStation/issues
