### ISSUE TITLE
[Mapping Issue] This vent and scrubber set really pisses me off

### ISSUE THREAD

**Issue by Tename** [Yawn-Wider/YWPolarisVore#635]
#### Brief description of the issue
Its under a door, vents don't work under doors, it also looks really wonky.

#### What you expected to happen
Not to be under a door

#### What actually happened
Its under a door

#### Steps to reproduce
- Walk between the paramedic office and bridge
- Look at the two double doors
- Die internally

#### Code Revision
Server revision: - 2020-03-05 

16066536a49d49965ae449284e7f837ec03736ec 
 
#### Anything else you may wish to add:
https://i.gyazo.com/57bae645db72474826b7492069b99821.png
I'd fix this if I wasn't lazy, but I am... It'll probably piss me off enough in a day or so to be bothered to make a fork and fix it though.

**Comment by Repede** [comment]
Fixed on master
