### ISSUE TITLE
[Mapping issue] The  pipes next to the elevator are not properly lined up

### ISSUE THREAD

**Issue by Tename** [Yawn-Wider/YWPolarisVore#637]
#### Brief description of the issue
Pipes next to the elevator are not properly lined up.

#### What you expected to happen
Climb up and down the pipes

#### What actually happened
Wall in the way

#### Steps to reproduce
- Go to the pipes next to the elevator
- Try to go down
- Wall in the way
- Ghost
- Go down
- Realize its not lined up right

#### Code Revision
Server revision: - 2020-03-05 

16066536a49d49965ae449284e7f837ec03736ec 
 
#### Anything else you may wish to add:
https://i.gyazo.com/8c996c08f9dbca29bc4fab20228183a3.png
https://i.gyazo.com/bee15376cf583d26b51fd7517df09fa9.png

**Comment by SplinterGP** [comment]
that's on the surface level, the underground 1 to midpoint and underground 1 are fine

**Comment by Tename** [comment]
Honestly, the level names always confuse me and I didn't want to look dumb by calling them level 0 and -1.

**Comment by Tename** [comment]
But ya, thats right.
