### ISSUE TITLE
"Underground rock" Area Power Alarms

### ISSUE THREAD

**Issue by KillianKirilenko** [Yawn-Wider/YWPolarisVore#648]
#### Brief description of the issue
There's an "underground rock" area that periodically pops up on power monitoring and causes a pointless power alarm. Turns out it's a small storage closet that isn't properly hooked into the power grid.

#### What you expected to happen
The room to have a proper area and to be connected to the power grid.

#### What actually happened
It isn't, so it'll pop power alarms when the unconnected APC inevitably runs out.

#### Steps to reproduce
- Look at the APC!
- It's not connected to the grid!
- Marvel at the fact it creates a power alarm.

#### Code Revision
Server revision: - 2020-03-09 
578367105c04f871ac5b03622d7acaef9a92bfd1 

#### Anything else you may wish to add:
- This is just north-east of the dorms, on "Deck 2".
![image](https://user-images.githubusercontent.com/49700375/76294145-39171d80-62aa-11ea-8d8f-4accd5d20ad3.png)

**Comment by RadiantFlash7** [comment]
Ahah! I have been wondering where the blazes this was.
