### ISSUE TITLE
pilot is civilian, not exploration, on the manifest

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#649]
#### Brief overview of the feature
Pilot isn't exploration crew and should not be on exploration crew on the manifest so the RD stops having to ask who are they responsible of and needs to ask OOCly how are things supposed to work on this station.

https://cdn.discordapp.com/attachments/278273342438375425/687006389905653806/unknown.png

https://cdn.discordapp.com/attachments/278273342438375425/687007671244816478/unknown.png

https://cdn.discordapp.com/attachments/644996409829097512/687011389918806068/unknown.png

#### What you want to happen
The Pilot appears in the Civilian tab of the in-game manifest, not on exploration's
 
#### Anything else you may wish to add:
A conversation about exploration, the shuttle, and the responsibilities/roles has been had on the discord to clear a couple things out, leading me to ask this small edit on the pilot's place on the manifest, as the wiki and the game contradict each other.

**Comment by izac112** [comment]
same would apply for search and rescue seeing as they are under medical

**Comment by izac112** [comment]
#650
