### ISSUE TITLE
Paramedic bay has a records console and a records laptop right next to each other

### ISSUE THREAD

**Issue by yeayea130** [Yawn-Wider/YWPolarisVore#652]
#### Brief description of the issue
In the paramedic bay there are two records devices right next to each other

#### What you expected to happen
The console to be a crew monitoring console.

#### What actually happened
The console was a medical records console

#### Steps to reproduce
- Go into the paramedic bay

#### Code Revision
- Server revision: - 2020-03-09 

578367105c04f871ac5b03622d7acaef9a92bfd1 
 
#### Anything else you may wish to add:
- Picture of the abformentioned console and laptop
![Screenshot_77](https://user-images.githubusercontent.com/62041596/76372329-6ea42100-6313-11ea-9f3b-0ded45d1a62c.png)

**Comment by RadiantFlash7** [comment]
Fixed in dev.
