### ISSUE TITLE
Not able to skydive from Borealis majoris 2 skies

### ISSUE THREAD

**Issue by SplinterGP** [Yawn-Wider/YWPolarisVore#655]
#### Brief description of the issue
Can't use parachutes to skydive from borealis majoris 2 skies and for some reason it also uses space transit on the way to it

#### What you expected to happen
not die when skydiving from where sounds like cryogaia skies

#### What actually happened
dudes got deleted to death

#### Steps to reproduce
- (Step 1)go to borealis majoris 2 skies
- (Step 2)jump with a parachute
- (and so on)blam you ded

#### Code Revision
erver revision: - 2020-03-11 

c9ee248f5b92187afc2036f0dba528644e21f9f3 
 
#### Anything else you may wish to add:
The borealis majoris 2 skies are probably not mapped as above cryogaia, so you just fall into nowhere

**Comment by RadiantFlash7** [comment]
Ah what? I thought I fixed that ;-;

**Comment by benj8560** [comment]
I think this can get closed since it's no longer a issue with new shuttle code.

**Comment by SplinterGP** [comment]
closed since we don't have borealis majoris 2 skies, but could still have tho
