### ISSUE TITLE
Security pilot Officer Job

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#657]
#### Brief overview of the feature
Security pilot officer job.
Flies Security interceptor shuttle, (heads to a few locations, formerly labor camp shuttle)
Pilots Security Rover. Mecha like 4 wheel vehicle that moves quickly in the snow, intended for snow patrols.

#### What you want to happen
Add New job for security stuff.
 
#### Anything else you may wish to add:
- (Pilots area within security, to be added in a blank tiled maint spot.)

**Comment by SplinterGP** [comment]
I think it could be easily added, also by the name interceptor shuttle it should be able to intercept shuttles?

**Comment by izac112** [comment]
Yes

**Comment by KillianKirilenko** [comment]
When I read 'rover' I pictured something that uses the shuttle system to emulate a ground vehicle and honestly? That could be a kinda neat way to introduce people to low-level exploration too. Just drive off into the snow and look for old research camps or spider nests or something.

**Comment by izac112** [comment]
This wont be that.

**Comment by SplinterGP** [comment]
i think the rover is one of the mech vehicles you can make, if not a new one, but yeah, a mech.

**Comment by KillianKirilenko** [comment]
I'm aware, on both counts. That's why I specified using the shuttle systems to emulate a seperate vehicle.

Honestly, unless Polaris/Virgo has fixed up the rover/tug vehicle stuff recently I wouldn't touch it with a ten foot pole. Last I heard it was super, super janky when it came to buckling. Like 'teleport across the map' janky.

**Comment by izac112** [comment]
it be a mech type anyways because he wanted robotics to be able to upgrade it and such anyways, so no need to worry about that.

**Comment by RadiantFlash7** [comment]
Yeah. I want to give the rover a taser/weapons systems and for it to be immune to Blizzards. Sort of important.

**Comment by KillianKirilenko** [comment]
Currently setting this up now. Any requirements or requests for special starting equipment? Pilot helmet? Unique jumpsuit? Alternate titles? Slot limit? etc.

So far I've added the new job, outfit, a new access level, and added the job to loadout options.

**Comment by SplinterGP** [comment]
Probably wait for it to be added the shuttle and stuff, but can already merge the things if theyre not joinable/getable.

**Comment by RadiantFlash7** [comment]
@KillianKirilenko Thanks for the assistance on this. My life's been hell the past month with work.
