### ISSUE TITLE
Drone pod event Broke

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#658]
#### Brief description of the issue
Event triggers a runetime error, and doesn't appear to spawn a droppod. 

#### What you expected to happen
Drone droppod lands.

#### What actually happened
No droppod ever deployed.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Needs to be coded for surface map areas on this server. Currently, it's for tether's surface decks to land at.

**Comment by SplinterGP** [comment]
Probably got borked after another upstream update, it was working fine before

**Comment by TheFurryFeline** [comment]
Are there any landmarks mapped in? https://github.com/Yawn-Wider/YWPolarisVore/blob/dbae1367c59691d836fffcfcf443f39dbe400f3c/code/modules/events/drone_pod_vr.dm#L11

**Comment by SplinterGP** [comment]
We probably dont have landmarks because it was pretty fine with them landing randomly, probably going to let them random drop back

**Comment by SplinterGP** [comment]
It got changed from upstream

**Comment by TheFurryFeline** [comment]
Yep, that's your issue, mapping related unless you want to revert it back to the old version

**Comment by RadiantFlash7** [comment]
Iii’ll fix it soon enough
