### ISSUE TITLE
Robotics missing items

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#673]
#### Brief description of the issue
robotics is missing some important things

#### What you expected to happen
Robotics to be stocked from round start with these items: A drill for installing NIF's in synthmorps and a medical record laptop for checking augment related records/synth records, Also could be worth moving the jumper cables from the aesthetic closet to somewhere more visible since most players if not all just think we don't have one. 

#### What actually happened
stuffs not there

#### Steps to reproduce
- (Step 1) Walk into robotics.
- (Step 2) See the missing items and go cry about it

#### Code Revision
dd75f9948c12f8e2fcdd567c519b6d075d7f840e 
 
#### Anything else you may wish to add:
Awoo

**Comment by Repede** [comment]
Fixed in master
