### ISSUE TITLE
Jukebox Issues

### ISSUE THREAD

**Issue by the-og-gear** [Yawn-Wider/YWPolarisVore#68]
#### Brief description of the issue
Jukebox sometimes doesn't play songs, or just doesn't play them at all.

#### What you expected to happen
I expected every song to work in the jukebox, I dunno what else would be expected.

#### What actually happened
Some songs just don't. It's like the record is missing or something.

#### Steps to reproduce
- Get a jukebox (of any sort, be it pre-spawned, admin spawned and initialized, or built)
- Open the interface
- Select one of the songs listed in "Anything else you may wish to add"
- Listen as it doesn't play

#### Code Revision
Server revision:  - 2019-01-26
ca23dabb150ea3292408b366c3edb0be412a03c1 
 
#### Anything else you may wish to add:
Songs that aren't working:
Song Title                                | Artist
---------------------------------|------
Rararasputin                            | Boney M
Don't Stop Me Now                | Queen
Knights of Cydonia                  | Muse
Baker Street                             | Gerry Rafferty
I Need a Hero                          | Bonnie Tyler
What a Wonderful World        | Louis Armstrong
Fortunate Son                          | Credence Clearwater Revival
Bad Moon Rising                     | Credence Clearwater Revival
Down on the Corner                | Credence Clearwater Revival
Have You Ever Seen the Rain   | Credence Clearwater Revival
Summer of 69                           | Bryan Adams
Heaven                                      | Bryan Adams
(Everything I Do) I Do it for You| Bryan Adams
Heroes                                       | David Bowie

Also have it in a nicely formatted table in case it doesn't format in issues and only in READMEs

**Comment by izac112** [comment]
Well the way the jukebox works is off direct links to the internet to the sound file and I would guess that the links for the songs that dont work have been moved/taken down etc
To fix this ace would just have to update the links

**Comment by Hawk-v3** [comment]
Oh is that how that works? Well, we could fix it ourselves. I'm going to assume this is more on upstream, but we'll see if it's still right.

**Comment by Hawk-v3** [comment]
This can be fixed if people give songlinks to Ace, so this one's all closed up as it's not on my side and not my issue/
