### ISSUE TITLE
Optical Mesons and Goggles.

### ISSUE THREAD

**Issue by Hawk-v3** [Yawn-Wider/YWPolarisVore#7]
Originally Submitted by Pixelnator

https://github.com/Repede/YawnWiderStation/issues/180

**Comment by DeepIndigo** [comment]
Possible solution: I could respite goggles to be like swimming goggles

**Comment by Hawk-v3** [comment]
Yeah, that could work. If you allow for... Uhn, look at how the chemical bottles are coloured? That way we can use a flexi overlay to show "Phoron-Sealed Meson Goggles" or whatever

**Comment by izac112** [comment]
Closing all issues from the old repo with not enough information.
