### ISSUE TITLE
Selecting spring in the autolathe creates a gear

### ISSUE THREAD

**Issue by Repede** [Yawn-Wider/YWPolarisVore#706]
#### Brief description of the issue
Title

#### What you expected to happen
To get a spring part in the autolathe

#### What actually happened
You get gears instead

#### Steps to reproduce
- Go to autolathe
- Select spring
- Get gear

#### Code Revision
2020-04-17 
500823710decf5150c2c14306c5d40cc4b10d00b

**Comment by izac112** [comment]
is fixed apparently
