### ISSUE TITLE
log exports for cargo

### ISSUE THREAD

**Issue by Tasald** [Yawn-Wider/YWPolarisVore#720]
#### Brief overview of the feature
Add a log processing machine to cargo, so the logging area has meaning. Maybe use the code for the smelter where it puts logs in one end and pops our 'processed wood, or something to sell on the shuttle but has no usage on station. This would also give loggers 'mining points' if it used the smelter machine. also rename the smelter to something else.

#### What you want to happen

 have the logging part of the station be useful to cargo.

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
Would be as easy as just adding a cp value to logs and planks, as for the machine to chop up the logs to planks automatically would be neat.

**Comment by Tasald** [comment]
I don't think planks would be a good idea unless cargo ordering gets changed. can already order planks from cargo, or make them your self, 2 per log, so was thinking some other item would make more sense to ship out?

**Comment by KillianKirilenko** [comment]
Easy solution; alien wood processor/phoron extractor.

In: Alien Wood
Out: Processed Wood, Phoron

Export phoron for points, keep wood for other projects.

**Comment by izac112** [comment]
True, lore wise logs probably would make more sense anyways.

**Comment by Tasald** [comment]
where's the phoron comeing from in the logs? it's an oxygen atmos not phoron?

**Comment by SplinterGP** [comment]
The woods in borealis are rich in phoron due to big deposits of phoron underground

**Comment by Tasald** [comment]
neat

**Comment by izac112** [comment]
Actually the wood just has a very high "burnability" seperating phoron from the wood is not really in spirit of how it was intended iirc tho only @RadiantFlash7 can say in the end how he wants this to work exactly

**Comment by SplinterGP** [comment]
Thinking by now, we could do alot of interesting things with wood, generators per example
