### ISSUE TITLE
Only one Rapid Piping Device can function on the server

### ISSUE THREAD

**Issue by Laria-D2** [Yawn-Wider/YWPolarisVore#740]
#### Brief description of the issue
Once a rapid piping device is used all others become non functional

#### What you expected to happen
Be able to use more than a single RPD

#### What actually happened
Once an RPD is used it becomes the only one that works.. Ever

#### Steps to reproduce
- Use RPD
- Attempt to use another RPD
- Marvel at how the second one doesn't work

#### Code Revision
- 6e1f161a1590c78693a5ef47639fa23e99c35591 
 
#### Anything else you may wish to add:
- I think it's pretty easy to replicate, thank you for reading.

**Comment by izac112** [comment]
Still broken apprantly

**Comment by izac112** [comment]
Hunakos57: Aside makeing a click noise it makes nothing.
