### ISSUE TITLE
Armory button

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#750]
#### Brief overview of the feature
Add a override button to the red armory door.

#### What you want to happen
A button by red armory that opens the door. ID locked to HOS or Warden access. I believe the lacking of this was a oversight not intended and the tether had such a button if I recall twas handy.
 
#### Anything else you may wish to add:

**Comment by KillianKirilenko** [comment]
This is a more-complicated-than-you-think kind of issue because our Red/Tac Armory is actually much better equipped than Virgo's. The stuff you see in the main Armory bay? That's all of what you get in Virgo's Red Armory *and then some*.

If you need to break open the tactical armory then shit had better be hitting the fan pretty spectacularly. There's sets of some of the best non-voidsuit/hardsuit armor available in there along with some pretty rude weapons.

(That said if you really, **really** need the stuff in there and literally cannot push to code red, code yellow/violet/orange ought to do the trick just fine too; it checks for green/blue.)

**Comment by SplinterGP** [comment]
If i need to open red armory i just blast the doors

**Comment by benj8560** [comment]
fair mostly the only IC reason I can think for it existing is checking armory stock every so often  something the warden ''should'' be doing but not really a thing here due to lack of antags

**Comment by benj8560** [comment]
plus those who play sec like splinter would know better I almost never play sec outside of borgs and even then rare just figured it might have been a missed thing. On the idea of blasting it down however I believe high security airlock electronics auto bolt if you break them but I might be thinking of baycode here.

**Comment by SplinterGP** [comment]
Yeah, i hate having a baby lock in it, but yeah, blas it down, crowbar electronics and deconstruct ezpz considering theres an autolathe over there if needed.  Also the tactical armors arent that good they dont protect feet or hands, unless you guys put combat or swat gloves and boots in it

**Comment by SplinterGP** [comment]
Seeing as mobs hit hand and feet alot its pretty bad

**Comment by RadiantFlash7** [comment]
Echoing what Killian said here, They have the /exact/ reasoning a button was not included.  The tactical armoury is heavy duty stuff, and I explicitly left it unavailible for normal means. It's intentionally meant to keep security out unless theres a confirmed threat to the station, presumably from external forces.

Our normal armoury is already strong as is, and theres such a thing as acceptable use of force. 

As for you @SplinterGP, You're disappointing me here. This sort of this sort of thing is about 100% unacceptable for a head of security to be doing.
/PLEASE/ Do not go shooting doors you don't have access to, when theres a perfectly good way to open it following SOP. Whats the point in being a head of security, if you're not going to follow the law?
The obvious exception being an emergency, where there is litterally no time to flip the alert level. (And odds are, the tactical armoury only really needs to be used during events. Where there will more then likely be plenty of time.)

**Comment by SplinterGP** [comment]
no yeah i mean in a emergency, i never shot it out unless when we were testing, i was saying of a way of opening it in a very needed occasion, like, if AI goes rogue or something you might not want to raise alert level or can't do it

**Comment by benj8560** [comment]
well feel free to trash this then figured there might be a reason behind it. Only reason I came up with this idea was because the marksman energy rifle would be pretty effective for taking care of combat drones and Splinter does have a point part of the Rogue AI procedure is to do your best to not let the AI become aware that you know it's rogue but I can't think of many other situations where shooting at open would be a logical choice

**Comment by SplinterGP** [comment]
Yeah i already mentioned the LARP to be outside of red armory as it is pretty effective for drones and catch people running outside, could even give it to the sec pilot for OUTSIDE use

**Comment by SplinterGP** [comment]
But for people i heard its kekked, as it has no accuracy nearby and loses accuracy on range for whatever reason, not sure if that got fixed

**Comment by benj8560** [comment]
yeah it's rather well balanced I believe with the low fire rate might be worth moving it to a locker in the normal armory for that kinda thing.

**Comment by benj8560** [comment]
anyways a idea for another issue report or for someone to keep in mind I will just close this for now save someone else doing it.
