### ISSUE TITLE
Protean NIF's not repairing to full.

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#765]
#### Brief description of the issue
NIF's in proteans not auto repairing after joining the game.

#### What you expected to happen
Protean NIF's are unreparable as far as I am aware IG so they auto repair to 100 every time you join the game.

#### What actually happened
NIF ends up at 30% ish every time I join.

#### Steps to reproduce
 self-explanatory and I'm not sure anyone else is having this issue.

#### Code Revision

Server revision: B:-Using TGS- D:-Using TGS-
Commit: eb86cef7cfcc11a37f5f152671586f93afbd185a
TGS version: /tg/station 13 Server v3.2.6.3
DMAPI version: 3.2.1.0 

#### Anything else you may wish to add:
Character name is Minna Tang and Ckey is Benl8561 if you need to look at my character save file. Also already had a admin try var editing it to 100% and deleting it. Both failed to help in anyway.

**Comment by SplinterGP** [comment]
Tried using some NIF variant?

**Comment by SplinterGP** [comment]
Maybe looking at vorestation can find something about

**Comment by KillianKirilenko** [comment]
This came up in the Virgo discord the other day actually. Repairing it is impossible, but the start % should be semi-random. Your NIF will never actually *break* break, but there may be shifts where you have to be more careful with what you install and run.

**Comment by Dwaggy** [comment]
I must say though, that if it's a bio nif that's in the protean, 30 is a pretty damn low end ball park % of what to do with. Pretty sure that would instantly break on like 2 program installs
Then again I'm someone who relies heavily on nif and can destroy one pretty easily. XD

**Comment by SplinterGP** [comment]
Bio nifs have less durability? Damn,i mean, ive been mostly just using the default sec NIF and it takes some % to it, using the default job nif modules + a few ones takes 10% of a regular NIF to more depending on what you buy

**Comment by Dwaggy** [comment]
Yep. Normal nifd have 100 durability, snowflake admin spawned has 1000, and bio adaptive has like.. Either 50 or 30 or some really low crappy number like that.
If your not careful you can burn it out in like one shift of smaccing nifs in to it.
that size changer one? That takes like 30% out of it right there iirc. Or something crazy like that.

**Comment by KillianKirilenko** [comment]
Proteans have a bioadaptive by default, yes: any NO_SCAN species (so proteans, prommies, and xenochimera, of the readily-playable lot) require a bioadaptive.

Max NIF durability is 100 points; bioadaptive max is 75, and special is 1000. Bootlegs are just 10, so skip that trash!

**Comment by SplinterGP** [comment]
Time to give wilson a bootleg

**Comment by benj8560** [comment]
has not been RNG based at all it has been in the 27-29% range for some time now every time and i think that is just due to boot up calsing a small amount of damage. Likely just gonna drag all my stuff over to another slot and that should fix it. Thankfully it has not been to much of a issue since I only really use it for APC charging and once in a blue moon pressure seals since proteans+voidsuits is kinda broken.

**Comment by benj8560** [comment]
annoying regardless so figured it's worth dropping here.

**Comment by KillianKirilenko** [comment]
Well NIFs are primarily a Virgo thing, so if you feel it's that much of a genuine/significant issue then I suggest taking it up with them.

**Comment by benj8560** [comment]
I asked a admin if I should go to VS or are github with it and they said here. Might need to get my player data to them since I got no idea if this has or will happen to anyone else. They told me just go here so ye. I already copied my stuff over to a new slot and that as I would expect fixed it.

**Comment by benj8560** [comment]
dunno could just ignore it for now and if it starts cropping up more then come back to it.

**Comment by benj8560** [comment]
an update: Made a new char slot and copied everything over that worked for a few rounds but the issue came back again

**Comment by Dwaggy** [comment]
https://github.com/Yawn-Wider/YWPolarisVore/blob/master/code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm line 153.
```
	spawn(0) //Let their real nif load if they have one
		if(!H) //Human could have been deleted in this amount of time. Observing does this, mannequins, etc.
			return
		if(!H.nif)
			var/obj/item/device/nif/bioadap/new_nif = new()
			new_nif.quick_implant(H)
		else
			H.nif.durability = rand(21,25)
```
It'll randomly set your durability between 21 to 25 it looks like once you wear it down.
So..yeah. if its staying around that area. its acting as intented.
and given that 21/25 is in actual specific durability out of 75 for the bioadapt, then.. yeah. that'd be around 30% give or take.
So..
acting as intended as far as i can see.
your getting the benifit of always garunteed to have one, and have one never break, at the cost of it starting at 30% all the time. its instead of making another nif type with only 25 durability. 
downside is it shows it as 30% instead of 100%. same effect though.

**Comment by benj8560** [comment]
ahh ok so it's just dumb fucking coding and nothing has changed?

**Comment by benj8560** [comment]
weird that I had it showing 100% for a shift or 2

**Comment by Dwaggy** [comment]
According to the blame tool, its not been changed since the protean was introduced 2 years ago.
And yeah. It'll spawn you with a brand spanky new one on the first shifts.
But then as you use it and play multiple times, it'll move to maintain the 30% or so.
weird coding. honestly it should probably be a unique bioadapt nif for it that just..you know. has 25 durability and go with that, in my opinion.. but.. 🤷 
Psychology looking at a nif and going 'its only 30% tho' and all, when in fact its always gunna be that.

**Comment by benj8560** [comment]
I can say 100% that it has not shown up as 30% until a few weeks or so  ago when I first reported it to a admin. So something must have changed

**Comment by KillianKirilenko** [comment]
More likely that some other *unrelated* thing was changed and that 'fixed' it, or your NIF was simply not saving its durability data properly.

Again: this has been reported on the Virgo discord & github, and was dismissed as functioning-as-intended: https://github.com/VOREStation/VOREStation/issues/7928

**Comment by izac112** [comment]
So this issue is moot then? can i lose it?

**Comment by Dwaggy** [comment]
issue is moot unless we want to raise the rand% durability that the protean nifs settle at.
