### ISSUE TITLE
Suggestion: move laser sniper for pilot

### ISSUE THREAD

**Issue by SplinterGP** [Yawn-Wider/YWPolarisVore#766]
#### Brief overview of the feature
Make the laser sniper rifle be sec pilot weapon instead, beinng useable for hunting criminals outside or drones.

#### What you want to happen
Move the sniper rifle to sec pilot on a preferably locked windoor thingy on their room

 
#### Anything else you may wish to add:
It would be a weapon the sec pilot could use for hunting criminals that run outside or help take out drones, i dont think it would be a problem and dont makes sense it be on red armory seeing it only causes 50 damage and 
10 armor pen, its also a extremely bulky weapon and can only be recharged at recharger(cant reload cell). From what i remember people running from sec or outside at wilderness are shoot to kill so it could be a sec pilot standard weapon for use OUTSIDE seeing is not a strong weapon at all other than scope. Could also be some long range stun sniper but i dunno

**Comment by izac112** [comment]
They have no more right to a laser sniper then any other sec officers, if they get a weapon they need to be issued it like every other officer, they are not really suppose to hunt the criminals themselves that is why there is seats for other officers in there.
