### ISSUE TITLE
Teleporter hub is broke, Particle accelerator is broken, trash piles are glitchy, mobs are acting weird, some tiles are without gravity

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#785]
#### Brief description of the issue
New bug : searching in the trash piles will now hide any item that was previously searched, instead of visually stacking them
if someone found a bottle of rhum but left it on the pile untouched, someone next finding a battery will have the bottle be invisible as the battery spawns on the pile

there's also the AI of mice, spiders, mobs in general that all either move in a synchronous fashion like robots, in the same direction, at the same moment in some weird mice choregraphy in maint, or don't move at all
spiders will remain mooostly still and immobile for extended periods of time, staying silent, until they suddenly see you

The teleporter station, hub don't connect to the control console anymore, the code has changed for them and now the console does all the station stuff, the world spawn one is connected but building a new one doesn't connect, interestingly though it does work with the hand tele though even though it shows not connected.
The station and hub also can't be dismantled

The particle accelerator's console will not react upon scanning for it's parts, and is completely unusable.

There is a space tile in excursion shuttle lobby, same with  the mime room (the maint room with a crate full of mime gear next to the chapel), and apparently in the exploration shuttle as well, /with no gravity/

https://cdn.discordapp.com/attachments/703775704814452811/716498266014875718/unknown.png
https://media.discordapp.net/attachments/703775704814452811/716498766449868810/unknown.png

#### What you expected to happen
for items to not hide each other like before,
for mobs to have a proper roaming AI like before,
For the particle accelerator to work like before,
for gravity to not turn off on random tiles OR make it a bluespace anomaly event if you really want to, eh

#### What actually happened
It's broken

#### Steps to reproduce
Play the game

**Comment by izac112** [comment]
This really should be split in to several issues

**Comment by Dopiotl** [comment]
I'll do that.

**Comment by Dopiotl** [comment]
Feel free to delete this one
