### ISSUE TITLE
Particle Accelerator is broken

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#786]
#### Brief description of the issue
The particle accelerator's console will not react upon scanning for it's parts, and is completely unusable.

#### What you expected to happen
For the particle accelerator to work like before

#### What actually happened
it won't find any of the parts of the PA assembly despite being assembled dutifully

#### Steps to reproduce
play the game

**Comment by izac112** [comment]
Next time we do a update this should be fixed: https://github.com/VOREStation/VOREStation/pull/8068

**Comment by izac112** [comment]
Should be fixed if  its not comment here and i reopen it
