### ISSUE TITLE
Teleporter is broken

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#789]
#### Brief description of the issue
The teleporter station, hub don't connect to the control console anymore, the code has changed for them and now the console does all the station stuff, the world spawn one is connected but building a new one doesn't connect, interestingly though it does work with the hand tele though even though it shows not connected.
The station and hub also can't be dismantled

#### What you expected to happen
To be able to use and work with the teleporter next to the bridge as intended

#### What actually happened
It's broken

#### Steps to reproduce
Play the game

**Comment by izac112** [comment]
So related to this. 
https://github.com/VOREStation/VOREStation/pull/7703

**Comment by Laria-D2** [comment]
Just woke up but not sure, the nano ui doesn't show them connected in it's window, they are still required for the hand tele to work however, they also can't be disassembled, only the console computer.
