### ISSUE TITLE
SweatMAX has had their protein shakes reduced, resulting in shortage

### ISSUE THREAD

**Issue by Laria-D2** [Yawn-Wider/YWPolarisVore#800]
#### Brief description of the issue 
Sweat Max protein shakes have been cut in half meaning every shift they're empty before hour 10 if there are any hungry races on

#### What you expected to happen
Apparently we were supposed to have more? And to NOT spam click and get air dispensed

#### What actually happened
No protein shakes by hour 10, air despensed.

#### Steps to reproduce
View the old code

`/obj/machinery/vending/fitness
	name = "SweatMAX"
	desc = "Fueled by your inner inadequacy!"
	icon_state = "fitness"
	products = list(/obj/item/weapon/reagent_containers/food/drinks/smallmilk = 8,
					/obj/item/weapon/reagent_containers/food/drinks/smallchocmilk = 8,
					/obj/item/weapon/reagent_containers/food/drinks/glass2/fitnessflask/proteinshake = 16,	//VOREStation Edit,
					/obj/item/weapon/reagent_containers/food/drinks/glass2/fitnessflask = 8,
					/obj/item/weapon/reagent_containers/food/snacks/candy/proteinbar = 8,
					/obj/item/weapon/reagent_containers/food/snacks/liquidfood = 8,
					/obj/item/weapon/reagent_containers/pill/diet = 8,
					/obj/item/weapon/reagent_containers/hypospray/autoinjector/biginjector/glucose = 5, //VOREStation Removal, YW Readdition,
					/obj/item/weapon/towel/random = 8)`
View the new code

`/obj/machinery/vending/fitness
    name = "SweatMAX"
    desc = "Fueled by your inner inadequacy!"
    icon_state = "fitness"
    products = list(/obj/item/weapon/reagent_containers/food/drinks/smallmilk = 16,
                    /obj/item/weapon/reagent_containers/food/drinks/smallchocmilk = 16,
                    /obj/item/weapon/reagent_containers/food/drinks/glass2/fitnessflask/proteinshake = 8,
                    /obj/item/weapon/reagent_containers/food/drinks/glass2/fitnessflask = 8,
                    /obj/item/weapon/reagent_containers/food/snacks/candy/proteinbar = 16,
                    /obj/item/weapon/reagent_containers/food/snacks/liquidfood = 8,
                    /obj/item/weapon/reagent_containers/pill/diet = 8,
                    /obj/item/weapon/reagent_containers/hypospray/autoinjector/biginjector/glucose = 5, //VOREStation Removal, YW Readdition,
                    /obj/item/weapon/towel/random = 8)`
#### Code Revision
d8362ebbdf7539c7c51ce9719cc509a49d129f8f  
#### Anything else you may wish to add:
It went from 16 to 8, some races live off that stuff so the new lower number gets drained very quickly.

**Comment by izac112** [comment]
Have a bunch of other stuff now in the machine  negating the need for this fix
