### ISSUE TITLE
pilot job is civilian crew, not exploration

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#810]
#### Brief description of the issue
It's been fixed before, but the pilot is once again back into exploration crew on the manifest. Can this be fixed, again?

#### What you expected to happen
For a previously adressed issue not to revert

#### What actually happened
Can this be fixed again please

#### Steps to reproduce
Play the game

**Comment by izac112** [comment]
Its part of both civilian and exploration
