### ISSUE TITLE
Bring back AI drone-use/make AI borg shells great

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#82]
#### Brief overview of the feature
So, as it stands, vorecoders, in yet another kick to the bits to AI players, as virtually everything they do related to AIs is, have removed AI drone use in favor of an "AI inteface" brain for borgs. Here's the rub: by all appearances, this requires intellicore transfer, rendering the new feature prohibitively crippled and frankly, pointless. 

#### What you want to happen
What I propose is either A: making this new AI interface gizmo work the way the maint drones did: AI can click to shunt-in malf style, then use the "release control" verb to bop back out to their core; or B:  bringing back AI control of maintenance drones
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Dwaggy** [comment]
Turns out that the control verbs were for some reason disabled in the controller configs.
will be fixed with #83 
c:

**Comment by Hawk-v3** [comment]
Merged.
