### ISSUE TITLE
the particle accelerator is broken

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#820]
#### Brief description of the issue
scanning for parts will not allow the console to detect them upon assembly

https://cdn.discordapp.com/attachments/247070327497031680/722855116863963146/unknown.png

#### What you expected to happen
For the console to be able to detect the complete assembly and to work as intended

#### What actually happened
scanning for parts will not allow the console to detect the assembly

#### Steps to reproduce
1-assemble a PA
2-Scan for the complete assembly
3-scanning for parts will not allow the console to detect the assembly

**Comment by Dopiotl** [comment]
This is a repost since my previous post about it has been closed but the issue is still there

**Comment by izac112** [comment]
rip apparently its not fixed then, for future reference you can just comment on your old post and i reopen it for next time.

**Comment by izac112** [comment]
Tested and its working fine

**Comment by Dopiotl** [comment]
I've found out the stupid way that the grids now spawn on shift start in the opposite places because fuck me in particular. So that's that. I'm just bad. The PA works just fine and I am a very stupid person
