### ISSUE TITLE
Rapid Piping Device heat pipes have no sprite

### ISSUE THREAD

**Issue by Laria-D2** [Yawn-Wider/YWPolarisVore#822]
#### Brief description of the issue
Heat exchange pipes made using the rapid piping device (hand held item) have black colorless item sprites that turn invisible when wrenched down, the big bulky pipe layer in atmos does not have this issue

Update: They aren't colorless, in fact they use the rpd's ability to color pipes and that's the problem, these pipes don't support color and the color selector doesn't have their color.

#### What you expected to happen
See the heat pipes used when using the rpd

#### What actually happened
invisible pipes that can't be wrenched up (without turf select) or viewed (Without being wrenched up), their sprites prior to wrenching use pipe colors

#### Steps to reproduce
- Grab rpd
- open menu and under heat exchange select pipe or junction
- Place pipe with wrench mode off, notice how the sprite doesn't match the regular pipes the bulky pipe dispenser makes
- Wrench it down and watch it dissapear.
#### Code Revision
- b1bec93e77d71484d1b0f08344845b1864007616 
 
#### Anything else you may wish to add:
- I updated the post, I believe this is related to the rpd's ability to paint pipes, it can even paint some things you wouldn't expect it too like omni pipe fittings (Which looks cool by the way).

**Comment by SplinterGP** [comment]
This happened twice

**Comment by Laria-D2** [comment]
Oh did I not see a previous report? Weh I thought I checked for one, though I did make sure that this only effects the RPD and that it's still in effect post fix (Since we can now use all rpds instead of only one), I really think it's just a directory issue, the rpd isn't calling for the right sprite for the item it places or is adding erroneous color tags to them making them invisible because they don't support color?

**Comment by SplinterGP** [comment]
i'll take a look and try to see what was the fix last time and see if the bug is the same as last, and fix it
