### ISSUE TITLE
Knowing everything and nothing, or how the Zaddot knows not how to speak their native language.

### ISSUE THREAD

**Issue by Sgtwok** [Yawn-Wider/YWPolarisVore#84]
#### Brief description of the issue
The new Zaddot species, while they can speak and select their native language of 'vedahq', seem to be unable to actually understand it. 

#### What you expected to happen
I expected the ability to know what I'm saying.

#### What actually happened
I have no clue what I am saying while speaking vedahq. While this is reflective of real life, this really seems kind of odd in-game.

#### Steps to reproduce
- (Step 1) Play a zaddot.
- (Step 2) Speak vedahq
- (Step 3) Cry because you can't talk to your fellows

#### Code Revision
Server revision:  - 2019-04-10
31fdbb06de0f002c04247042a118e1cfc9058cb0 
 
#### Anything else you may wish to add:
Generalpantsu noted that while ghosted, they saw the ',z' required to speak the language as well, but they could also at least understand it.

**Comment by Dwaggy** [comment]
Looks like its a conflict in keybinds.
Both Vedahq and Sagaru use ,z as their language key.
and if you have both languages, Sagaru is used.

**Comment by Hawk-v3** [comment]
I'll have a look at it. I assume the keybinds just need changing.
