### ISSUE TITLE
Beef up muh rescue rig

### ISSUE THREAD

**Issue by benj8560** [Yawn-Wider/YWPolarisVore#855]
#### Brief overview of the feature
Add heat resist to the rescue rig so medical is actually equipped to deal with somebody stuck in a blizzard. It's very silly to have a every day hazard that medical is not equipped to deal with.

#### What you want to happen
^
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Could even go as far as to add this to ALL medical suits or add  a new suit type just for it. However the RIG is intended for hostile environments so it seems the most fitting.

**Comment by izac112** [comment]
sadly the way the blizzard currently applies damage that wont happen because the only way to make the suit immune to it is to give it complete fire immunity like a fire suit or a atmos rig and the rescue rig wont get that, though reworking the blizzard code is something we plan to do in the future.
