### ISSUE TITLE
wall geiger placed in "maintenance"

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#856]
#### Brief description of the issue
it's in the title
The geiger is at the cryogenics storage door, see the screenshot

https://cdn.discordapp.com/attachments/703775704814452811/730380175102967858/unknown.png

#### What you expected to happen
for the wall geiger to start screaming during a radstorm, as intended

#### What actually happened
it somewhow was considerd to be in maint and kept quiet

#### Steps to reproduce
1 - have a radstorm
2-this specific wall geiger won't report any radiation

**Comment by SplinterGP** [comment]
Thats actually because cryogenics is radiation proof apparently

**Comment by SplinterGP** [comment]
so its not a issue with the geiger

**Comment by Laria-D2** [comment]
I like that cryo is radiation proof, can this be extended to the public teleporters as well? We need some sort of 'spawn protection' so it would make sense to add all player spawn locations to the shielding. (If it already is and I just haven't noticed it yet then disregard)
