### ISSUE TITLE
Toggle-able tails/wing visibility.

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#885]
#### Brief overview of the feature
Add the ability for the visibility of wings/tails to be toggled.

#### What you want to happen
A verb that toggles the visibility of tails and wings (basically hide them like the rad suit does but without the rad suit). One verb for tails, one for wings.

**Comment by SplinterGP** [comment]
something i just imagined on mind was someone hiding their entire taur-tail xD, just a thing to watch when coding then.

**Comment by izac112** [comment]
As long as flight has a check to make sure you cant fly while having them hidden sounds like a good idea

**Comment by izac112** [comment]
https://github.com/VOREStation/VOREStation/pull/13569
https://github.com/VOREStation/VOREStation/pull/10094
