### ISSUE TITLE
The arrival announcement computer is broken and sometimes muted

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#892]
#### Brief description of the issue
It's in the title.

#### What you expected to happen
For the arrival announcement computer not to be broken.

#### What actually happened
The arrival announcement computer is not working.

#### Steps to reproduce
play the game

**Comment by Dopiotl** [comment]
In this screenshot, this player's first log was them talking on the radio, they have not been announced when they joined the station

https://media.discordapp.net/attachments/671440199502397470/735568251110686760/unknown.png?width=943&height=496

**Comment by SplinterGP** [comment]
did you check if anyone else heard its arrival ? unless its frequent it could've been the chat that ate the message

**Comment by DeepIndigo** [comment]
Can confirm it don't work. I literally haven't heard people be announced when arriving by shuttle for a couple weeks now.

**Comment by izac112** [comment]
related to the shuttle teleporter and cryo is not included
