### ISSUE TITLE
materials FLoorSafe for science

### ISSUE THREAD

**Issue by Dopiotl** [Yawn-Wider/YWPolarisVore#897]
#### Brief overview of the feature
It's a simple floor safe in the RnD desk.

It should have the same access restriction than a science locker.

It should have huge capacity for the materials used by the science machines, can be loaded and taken thing from with a basic inventory menu that allows to take a select number of sheets, just like from the protolath or robotic printers.

I think it could be placed here
https://cdn.discordapp.com/attachments/703775704814452811/736348972008079360/unknown.png

#### Anything else you may wish to add:
Floor safe sprite I edited for it, here's the file
https://cdn.discordapp.com/attachments/644996409829097512/736348333765034124/floorsafe_sci.dmi

**Comment by izac112** [comment]
Science has the temporary sheet storage now
