### ISSUE TITLE
Change aerostat hivebots from laser to gauss

### ISSUE THREAD

**Issue by SplinterGP** [Yawn-Wider/YWPolarisVore#923]
#### Brief overview of the feature
Switch the op hivebots from aerostat to gauss

#### What you want to happen
People not getting instashot by OP mobs on aerostat, while gauss can also stun it seems more fair than never(almost) missing mobs that you cant dodge
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.) aerostat

**Comment by izac112** [comment]
Sorry not happening, though could up projectile_accuracy to minus -30 instead of minus -20 for the laser hivebots

**Comment by SplinterGP** [comment]
Even then its straight up OP as its a completely RNG chance you'll just get hit instantly without able to do anything

**Comment by SplinterGP** [comment]
While all the others youre able to use cover and all

**Comment by SplinterGP** [comment]
If they'd get gauss instead of laser they'd be more stronger yet more fair

**Comment by izac112** [comment]
Well i just tested it 3 different times and all three times i could very easily dodge 35% to 45% of the shots by just constantly moving up and down, then i took about 4 shots before going down as completely naked as a human,  again its suppose to be very dangerous they are hive bots and stat is not suppose to be a walk in the park.

They are staying laser.

**Comment by izac112** [comment]
best you get is 30 minus instead of 20

**Comment by izac112** [comment]
If you want to add a gauss variant to space out the spawns of lasers we could do that though

**Comment by RadiantFlash7** [comment]
Real talk. I’m hesitant to make any mob use gauss shots. Getting onehit stunned feels worse then getting instashot imo. Especially if any other mobs are around you get wasted.

**Comment by KillianKirilenko** [comment]
Agreed. Virgo and other downstreams recently removed stun-capable mobs from a couple of POIs/locations because they were *ruining* exploration teams.

Getting hit by hitscan lasers might suck, but I can assure you that stun effects will suck 100x more.

It might be better to increase the cooldown between shots or reduce the damage they deal instead, as each laser is 30 damage.
