### ISSUE TITLE
Map cryogaia-10-caves

### ISSUE THREAD

**Issue by izac112** [Yawn-Wider/YWPolarisVore#954]
Map cryogaia-09-wilderness
Assignees: @izac112
This is more for my VSCode Sanity and tracking and will be updated as needed
 - [ ] Make entrances from the wilderness Z
 - [ ] actually map the map

**Comment by Repede** [comment]
caves when 8)

**Comment by izac112** [comment]
Pain and suffering probably should just finish it i think the reason i stopped was because some active edges i wanted to deal with first that i never found a solution for, that i was happy with

**Comment by izac112** [comment]
Probably going to have to make it a submap too

**Comment by izac112** [comment]
That works
