### ISSUE TITLE
Load-out born communicators drop node connection

### ISSUE THREAD

**Issue by DeepIndigo** [Yawn-Wider/YWPolarisVore#961]
#### Brief description of the issue
When the exonet node powers down at all (via weather, power outage, etc), all comms brought into the game via loadouts immediately become "partially" disconnected.

#### What you expected to happen
Comms to pick up service again like NIFcommlinks and the comms that are on the map.

#### What actually happened
Comms enter a semi-disconnected state where they can receive texts and call invites, but not send either. They also can not answer incoming call invites.

#### Steps to reproduce
- Bring your comm to work
- Be at work when the node goes down for literally any reason
- Get a new space cellphone form research when yours inevitably stops working.

#### Code Revision
- Current as of typing this.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by DeepIndigo** [comment]
This appears to be fixed

**Comment by izac112** [comment]
Closing this then
