### ISSUE TITLE
Top floor Maintenance Walls

### ISSUE THREAD

**Issue by Erokusan** [Yawn-Wider/YWPolarisVore#970]
#### Brief description of the issue
The doors to those little rooms in maintenance have walls underneath them, and the doors are not powered

#### What you expected to happen
To open the door and receive maintenance shenanigans

#### What actually happened
Big fat walls, one of the walls is even reinforced steel

#### Steps to reproduce
- (Step 1)Open door with crowbar
- (Step 2)Receive wall
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Top floor, directly south of Explorers offices

**Comment by izac112** [comment]
I get a fix out, though they are meant not to be powered.
