### ISSUE TITLE
Door Errors with Exploration 

### ISSUE THREAD

**Issue by Liu-Junior** [Yawn-Wider/YWPolarisVore#975]
#### Brief description of the issue
A few doors from the new Exploration department have either bad accesses or are just not supposed to be those particular door. Also, one of the windows, just south of the corridor's door, doesnt seem to have a Ceiling tile, and as such would cause atmos issues if the inner window pannel would break.

 https://gyazo.com/7cf0517c6d8072afca0ee44e988f8177

#### What you expected to happen
Be an Explorer and be able to access my department without issue. 

#### What actually happened
I cannot open the door in the main corridor to Exploration, currently tagged as "Medical Diagnostics Center", nor access the Explorer Storage room containing all the explorer's equipment, which appears to be accessible only to the PathFinder.

#### Steps to reproduce
I don't really need to explain the steps, right?

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Yer a derp.

**Comment by Laria-D2** [comment]
Some doors also lack head access, and I saw a space tile underneath a maint door but was too tired to hack in and confirm it (I saw it with mesions and a space tile on the planet sticks out.)

**Comment by izac112** [comment]
head access lacking is intentional and the space tiles will be taken care of next restart along with this issue
