### ISSUE TITLE
Maintenance radiation

### ISSUE THREAD

**Issue by RadiantFlash7** [Yawn-Wider/YWPolarisVore#979]
#### Brief description of the issue
Several people have reported being irradiated despite being in maintenance

#### What you expected to happen
This not to happen

#### What actually happened
I’m not sure, exactly. We need to double check whether the radiation from the rad event is still stactic, or see if it spreads.
Another possibility is people getting partly irradiated, and then moving into maint next to everyone else irradiating them?

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- Does not seem to be a mapping issue- issues reported in bar maint, and lower level maintenance halls. Areas specified are correct and radproof.

**Comment by Laria-D2** [comment]
The easiest way to test if it's a rad event issue is to set down gieger counters in the places you wish to test, ghost and trigger the rad event, there's probably a smarter way to do it but that's my live in game take.

**Comment by RadiantFlash7** [comment]
Radiation proof tunnels work as intended. The reports are people getting irradiated, and walking into maints, irradiating other crew.

**Comment by SplinterGP** [comment]
actually there are a few maint tunnels that appear to not be protected, i will try to find them

**Comment by SplinterGP** [comment]
also radiation dont spreads to other people.

**Comment by RadiantFlash7** [comment]
> also radiation dont spreads to other people.

It should if someone is rradiated to a certain point, they give off radiation.

**Comment by RadiantFlash7** [comment]
> actually there are a few maint tunnels that appear to not be protected, i will try to find them

afaik the only unprotected tunnels is the one right next to sec that 2 tiles one, the one  next to the elevator,
and any sand tiles on the maint level.

**Comment by SplinterGP** [comment]
well never seen it ever happen of someone irradiated to heck to spread radiation, otherwise when medbay people were rescuing people with rads they would be affected too i wonder, also recently i remember staying on a maint, dont remember which one, i think was close to some medical part, and it wanst shielded, unless it got fixed on some PR it still has that maint without it, might have like 5 days that happened

**Comment by RadiantFlash7** [comment]
I'll double check all the apropriate maint tiles and make sure they have the correct areas. But I'm pretty sure they do.

**Comment by SplinterGP** [comment]
Check all maints around medbay, maybe it has an area that is a different path for whatever reason

**Comment by Repede** [comment]
Closing until more rad and maintenance issues are found
